### ISSUE TITLE
Selenium again crashing

### ISSUE THREAD

**Issue by Psychokiller1888** [project-alice-assistant/ProjectAlice#103]
Can we not get rid of that crap selenium and just use the endpoints instead of mocking a user browsing the console?

```
An unhandled exception occured
- Traceback: Traceback (most recent call last):
  File "main.py", line 89, in <module>
    main()
  File "main.py", line 75, in main
    projectAlice = ProjectAlice()
  File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 17, in __init__
    self._superManager.onStart()
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 86, in onStart
    samkillaManager.onStart()
  File "/home/pi/ProjectAlice/core/snips/SamkillaManager.py", line 63, in onStart
    self.sync()
  File "/home/pi/ProjectAlice/core/snips/SamkillaManager.py", line 109, in sync
    if not self.start():
  File "/home/pi/ProjectAlice/core/snips/SamkillaManager.py", line 151, in start
    self.login(self.ROOT_URL + '/home/apps')
  File "/home/pi/ProjectAlice/core/snips/SamkillaManager.py", line 194, in login
    self._browser.find_element_by_class_name('cookies-analytics-info__ok-button').click()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"class name","selector":"cookies-analytics-info__ok-button"}
  (Session info: headless chrome=72.0.3626.121)
  (Driver info: chromedriver=72.0.3626.121,platform=Linux 4.19.66-v7+ armv7l)
```

**Comment by Psychokiller1888** [comment]
To answer myself, yes we can get rid of selenium and chrom driver, as it is jwt based, maybe even the same token as the one retrieved by SnipsConsoleManager
