### ISSUE TITLE
restart loop after install Brinng skill

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#209]
After installing Bring skill then restarting, Alice audio continuously (every 30 sec or so) pings winth the same audio as restart with this in log
```
2020-03-02 19:46:39,693 [MainThread] - [INFO] - [Initializer] Starting Project Alice initializer
2020-03-02 19:46:39,695 [MainThread] - [INFO] - [Initializer] No initialization needed
2020-03-02 19:46:39,697 [MainThread] - [INFO] - [main] Starting up Project Alice
2020-03-02 19:46:40,339 [MainThread] - [INFO] - [Manager] Initializing Commons
2020-03-02 19:46:40,342 [MainThread] - [INFO] - [Manager] Initializing ConfigManager
2020-03-02 19:46:40,344 [MainThread] - [INFO] - [ConfigManager] Checking Alice configuration file
2020-03-02 19:46:40,346 [MainThread] - [INFO] - [ConfigManager] Loading Snips configuration file
2020-03-02 19:46:40,352 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill DateDayTimeYear
2020-03-02 19:46:40,354 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill IcanhazdadjokeDotCom
2020-03-02 19:46:40,356 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill Speedtest
2020-03-02 19:46:40,358 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill ContextSensitive
2020-03-02 19:46:40,360 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill Telemetry
2020-03-02 19:46:40,362 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill AliceCore
2020-03-02 19:46:40,364 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill Speller
2020-03-02 19:46:40,366 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill RedQueen
2020-03-02 19:46:40,368 [MainThread] - [INFO] - [ConfigManager] Checking configuration for skill Wikipedia
2020-03-02 19:46:40,372 [MainThread] - [INFO] - [Manager] Initializing DatabaseManager
2020-03-02 19:46:40,374 [MainThread] - [INFO] - [Manager] Initializing LanguageManager
2020-03-02 19:46:40,377 [MainThread] - [INFO] - [Manager] Initializing SnipsServicesManager
2020-03-02 19:46:40,379 [MainThread] - [INFO] - [Manager] Initializing ASRManager
2020-03-02 19:46:40,382 [MainThread] - [INFO] - [Manager] Initializing TTSManager
2020-03-02 19:46:40,385 [MainThread] - [INFO] - [Manager] Initializing ThreadManager
2020-03-02 19:46:40,388 [MainThread] - [INFO] - [Manager] Initializing ProtectedIntentManager
2020-03-02 19:46:40,391 [MainThread] - [INFO] - [Manager] Initializing MqttManager
2020-03-02 19:46:40,396 [MainThread] - [INFO] - [Manager] Initializing TimeManager
2020-03-02 19:46:40,399 [MainThread] - [INFO] - [Manager] Initializing UserManager
2020-03-02 19:46:40,401 [MainThread] - [INFO] - [Manager] Initializing DialogSessionManager
2020-03-02 19:46:40,404 [MainThread] - [INFO] - [Manager] Initializing MultiIntentManager
2020-03-02 19:46:40,407 [MainThread] - [INFO] - [Manager] Initializing TelemetryManager
2020-03-02 19:46:40,410 [MainThread] - [INFO] - [Manager] Initializing SkillManager
2020-03-02 19:46:40,413 [MainThread] - [INFO] - [Manager] Initializing DeviceManager
2020-03-02 19:46:40,416 [MainThread] - [INFO] - [Manager] Initializing InternetManager
2020-03-02 19:46:40,419 [MainThread] - [INFO] - [Manager] Initializing WakewordManager
2020-03-02 19:46:40,422 [MainThread] - [INFO] - [Manager] Initializing TalkManager
2020-03-02 19:46:40,424 [MainThread] - [INFO] - [Manager] Initializing WebInterfaceManager
2020-03-02 19:46:40,427 [MainThread] - [INFO] - [Manager] Initializing SnipsWatchManager
2020-03-02 19:46:40,430 [MainThread] - [INFO] - [Manager] Initializing NodeRedManager
2020-03-02 19:46:40,433 [MainThread] - [INFO] - [Manager] Initializing SkillStoreManager
2020-03-02 19:46:40,435 [MainThread] - [INFO] - [Manager] Initializing DialogTemplateManager
2020-03-02 19:46:40,439 [MainThread] - [INFO] - [Manager] Initializing SnipsAssistantManager
2020-03-02 19:46:40,442 [MainThread] - [INFO] - [Manager] Initializing NluManager
2020-03-02 19:46:40,449 [MainThread] - [INFO] - [NluEngine] Starting Snips NLU
2020-03-02 19:46:40,530 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-nlu start'ed
2020-03-02 19:46:40,532 [MainThread] - [INFO] - [Manager] Starting Commons
2020-03-02 19:46:40,534 [MainThread] - [INFO] - [Manager] Starting ConfigManager
2020-03-02 19:46:40,535 [MainThread] - [INFO] - [Manager] Starting LanguageManager
2020-03-02 19:46:40,537 [MainThread] - [INFO] - [LanguageManager] Active language set to "en-US"
2020-03-02 19:46:40,538 [MainThread] - [INFO] - [LanguageManager] Default language set to "en-US"
2020-03-02 19:46:40,541 [MainThread] - [INFO] - [Manager] Starting InternetManager
2020-03-02 19:46:40,743 [MainThread] - [INFO] - [Manager] Starting SnipsServicesManager
2020-03-02 19:46:40,824 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-hotword start'ed
2020-03-02 19:46:40,906 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-dialogue start'ed
2020-03-02 19:46:40,994 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-audio-server start'ed
2020-03-02 19:46:40,997 [MainThread] - [INFO] - [Manager] Starting DatabaseManager
2020-03-02 19:46:41,000 [MainThread] - [INFO] - [Manager] Starting UserManager
2020-03-02 19:46:41,004 [MainThread] - [INFO] - [UserManager] - Loaded 1 users
2020-03-02 19:46:41,006 [MainThread] - [INFO] - [Manager] Starting MqttManager
2020-03-02 19:46:41,010 [MainThread] - [INFO] - [Manager] Starting ASRManager
2020-03-02 19:46:41,382 [MainThread] - [INFO] - [ASR] Checking dependencies
2020-03-02 19:46:41,557 [MainThread] - [INFO] - [ASR] Starting Google ASR
2020-03-02 19:46:41,570 [MainThread] - [INFO] - [Manager] Starting TTSManager
2020-03-02 19:46:41,571 [MainThread] - [INFO] - [TTSManager] Started "pico" TTS
2020-03-02 19:46:41,573 [MainThread] - [INFO] - [TTS] Language from config: "en-US"
2020-03-02 19:46:41,575 [MainThread] - [INFO] - [TTS] Type from config: "male"
2020-03-02 19:46:41,576 [MainThread] - [INFO] - [TTS] Voice from config: "en-US"
2020-03-02 19:46:41,578 [MainThread] - [INFO] - [Manager] Starting ProtectedIntentManager
2020-03-02 19:46:41,579 [MainThread] - [INFO] - [Manager] Starting ThreadManager
2020-03-02 19:46:41,581 [MainThread] - [INFO] - [Manager] Starting TimeManager
2020-03-02 19:46:41,582 [MainThread] - [INFO] - [Manager] Starting DialogSessionManager
2020-03-02 19:46:41,584 [MainThread] - [INFO] - [Manager] Starting MultiIntentManager
2020-03-02 19:46:41,586 [MainThread] - [INFO] - [Manager] Starting TelemetryManager
2020-03-02 19:46:41,590 [MainThread] - [INFO] - [Manager] Starting DeviceManager
2020-03-02 19:46:41,593 [MainThread] - [INFO] - [DeviceManager] - Loaded 0 devices
2020-03-02 19:46:41,595 [MainThread] - [INFO] - [Manager] Starting WakewordManager
2020-03-02 19:46:41,596 [MainThread] - [INFO] - [Manager] Starting WebInterfaceManager
2020-03-02 19:46:41,598 [MainThread] - [INFO] - [WebInterfaceManager] Loaded interface in "en"
2020-03-02 19:46:44,082 [MainThread] - [INFO] - [Manager] Starting SnipsWatchManager
2020-03-02 19:46:45,097 [MainThread] - [INFO] - [Manager] Starting TalkManager
2020-03-02 19:46:45,129 [MainThread] - [INFO] - [Manager] Starting SkillManager
2020-03-02 19:46:45,137 [MainThread] - [INFO] - [SkillManager] Checking for skill updates
2020-03-02 19:46:45,145 [MainThread] - [INFO] - [SkillManager] ✔ DateDayTimeYear - Version 1.0.22 in master
2020-03-02 19:46:45,149 [MainThread] - [INFO] - [SkillManager] ✔ IcanhazdadjokeDotCom - Version 1.0.23 in master
2020-03-02 19:46:45,153 [MainThread] - [INFO] - [SkillManager] ✔ Speedtest - Version 1.1.2 in master
2020-03-02 19:46:45,155 [MainThread] - [INFO] - [SkillManager] ✔ ContextSensitive - Version 1.0.15 in master
2020-03-02 19:46:45,157 [MainThread] - [INFO] - [SkillManager] ✔ Telemetry - Version 1.1.2 in master
2020-03-02 19:46:45,158 [MainThread] - [INFO] - [SkillManager] ✔ AliceCore - Version 1.0.51 in master
2020-03-02 19:46:45,161 [MainThread] - [INFO] - [SkillManager] ✔ Speller - Version 1.1.0 in master
2020-03-02 19:46:45,163 [MainThread] - [INFO] - [SkillManager] ✔ RedQueen - Version 1.0.20 in master
2020-03-02 19:46:45,164 [MainThread] - [INFO] - [SkillManager] ✔ Wikipedia - Version 1.1.3 in master
2020-03-02 19:46:45,166 [MainThread] - [INFO] - [SkillManager] Found 0 skill update(s)
2020-03-02 19:46:45,295 [MainThread] - [INFO] - [AliceSkill] Loading 2 widgets
2020-03-02 19:46:45,299 [MainThread] - [INFO] - [AliceSkill] Loaded widget "Clock"
2020-03-02 19:46:45,302 [MainThread] - [INFO] - [AliceSkill] Loaded widget "Date"
2020-03-02 19:46:45,333 [MainThread] - [ERROR] - [SkillManager] Couldn't instantiate skill Speller.Speller: 'icon'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 216, in importFromSkill
    instance: AliceSkill = klass()
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 39, in __init__
    self._icon = self._install['icon']
KeyError: 'icon'
2020-03-02 19:46:45,371 [MainThread] - [INFO] - [AliceCore] Starting AliceCore skill
2020-03-02 19:46:45,496 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,498 [MainThread] - [INFO] - [SkillManager] Starting ContextSensitive skill
2020-03-02 19:46:45,501 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,503 [MainThread] - [INFO] - [SkillManager] Starting DateDayTimeYear skill
2020-03-02 19:46:45,506 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,508 [MainThread] - [INFO] - [SkillManager] Starting IcanhazdadjokeDotCom skill
2020-03-02 19:46:45,510 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,526 [MainThread] - [INFO] - [RedQueen] Starting RedQueen skill
2020-03-02 19:46:45,530 [MainThread] - [INFO] - [SkillManager] Found existing Red Queen identity
2020-03-02 19:46:45,532 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,533 [MainThread] - [INFO] - [SkillManager] Starting Speedtest skill
2020-03-02 19:46:45,536 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,537 [MainThread] - [INFO] - [SkillManager] Starting Telemetry skill
2020-03-02 19:46:45,540 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,542 [MainThread] - [INFO] - [SkillManager] Starting Wikipedia skill
2020-03-02 19:46:45,545 [MainThread] - [INFO] - [SkillManager] - Started!
2020-03-02 19:46:45,546 [MainThread] - [INFO] - [SkillManager] All skills started. 34 intents supported
2020-03-02 19:46:45,548 [MainThread] - [INFO] - [Manager] Starting DialogTemplateManager
2020-03-02 19:46:45,551 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "DateDayTimeYear"
2020-03-02 19:46:45,553 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "IcanhazdadjokeDotCom"
2020-03-02 19:46:45,555 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Speedtest"
2020-03-02 19:46:45,558 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "ContextSensitive"
2020-03-02 19:46:45,560 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Telemetry"
2020-03-02 19:46:45,562 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "AliceCore"
2020-03-02 19:46:45,578 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Speller"
2020-03-02 19:46:45,580 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "RedQueen"
2020-03-02 19:46:45,582 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Wikipedia"
2020-03-02 19:46:45,593 [MainThread] - [INFO] - [DialogTemplateManager] Cache uptodate
2020-03-02 19:46:45,595 [MainThread] - [INFO] - [Manager] Starting SnipsAssistantManager
2020-03-02 19:46:45,597 [MainThread] - [INFO] - [SnipsAssistantManager] Checking assistant
2020-03-02 19:46:45,599 [MainThread] - [INFO] - [SnipsAssistantManager] Assistant existing, check consistency
2020-03-02 19:46:45,624 [MainThread] - [INFO] - [SnipsAssistantManager] Assistant seems consistent
2020-03-02 19:46:45,626 [MainThread] - [INFO] - [Manager] Starting NluManager
2020-03-02 19:46:45,629 [MainThread] - [INFO] - [DialogTemplateManager] Cache cleared
2020-03-02 19:46:45,632 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "DateDayTimeYear"
2020-03-02 19:46:45,634 [MainThread] - [INFO] - [DialogTemplateManager] Skill "DateDayTimeYear" is new
2020-03-02 19:46:45,636 [MainThread] - [INFO] - [DialogTemplateManager] Skill "DateDayTimeYear" has new language support "en"
2020-03-02 19:46:45,638 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "IcanhazdadjokeDotCom"
2020-03-02 19:46:45,639 [MainThread] - [INFO] - [DialogTemplateManager] Skill "IcanhazdadjokeDotCom" is new
2020-03-02 19:46:45,641 [MainThread] - [INFO] - [DialogTemplateManager] Skill "IcanhazdadjokeDotCom" has new language support "en"
2020-03-02 19:46:45,649 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Speedtest"
2020-03-02 19:46:45,651 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Speedtest" is new
2020-03-02 19:46:45,653 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Speedtest" has new language support "en"
2020-03-02 19:46:45,655 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "ContextSensitive"
2020-03-02 19:46:45,656 [MainThread] - [INFO] - [DialogTemplateManager] Skill "ContextSensitive" is new
2020-03-02 19:46:45,658 [MainThread] - [INFO] - [DialogTemplateManager] Skill "ContextSensitive" has new language support "en"
2020-03-02 19:46:45,660 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Telemetry"
2020-03-02 19:46:45,662 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Telemetry" is new
2020-03-02 19:46:45,664 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Telemetry" has new language support "en"
2020-03-02 19:46:45,666 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "AliceCore"
2020-03-02 19:46:45,668 [MainThread] - [INFO] - [DialogTemplateManager] Skill "AliceCore" is new
2020-03-02 19:46:45,670 [MainThread] - [INFO] - [DialogTemplateManager] Skill "AliceCore" has new language support "en"
2020-03-02 19:46:45,672 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Speller"
2020-03-02 19:46:45,673 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Speller" is new
2020-03-02 19:46:45,675 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Speller" has new language support "en"
2020-03-02 19:46:45,677 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "RedQueen"
2020-03-02 19:46:45,679 [MainThread] - [INFO] - [DialogTemplateManager] Skill "RedQueen" is new
2020-03-02 19:46:45,681 [MainThread] - [INFO] - [DialogTemplateManager] Skill "RedQueen" has new language support "en"
2020-03-02 19:46:45,683 [MainThread] - [INFO] - [DialogTemplateManager] Checking data for skill "Wikipedia"
2020-03-02 19:46:45,685 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Wikipedia" is new
2020-03-02 19:46:45,687 [MainThread] - [INFO] - [DialogTemplateManager] Skill "Wikipedia" has new language support "en"
2020-03-02 19:46:45,691 [MainThread] - [INFO] - [DialogTemplateManager] Building dialog templates cache
2020-03-02 19:46:45,712 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for DateDayTimeYear
2020-03-02 19:46:45,718 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for IcanhazdadjokeDotCom
2020-03-02 19:46:45,722 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for Speedtest
2020-03-02 19:46:45,727 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for ContextSensitive
2020-03-02 19:46:45,732 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for Telemetry
2020-03-02 19:46:45,738 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for AliceCore
2020-03-02 19:46:46,022 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for Speller
2020-03-02 19:46:46,026 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for RedQueen
2020-03-02 19:46:46,035 [MainThread] - [INFO] - [SnipsNlu] Preparing NLU training file for Wikipedia
2020-03-02 19:46:46,040 [MainThread] - [INFO] - [SnipsNlu] Training Snips NLU
2020-03-02 19:46:46,530 [MainThread] - [INFO] - [SnipsNlu] Generated dataset for training
2020-03-02 19:46:46,532 [MainThread] - [INFO] - [SnipsNlu] Begin training...
2020-03-02 19:46:47,761 [MainThread] - [ERROR] - [SnipsNlu] Snips NLU training failed
NoneType: None
2020-03-02 19:46:47,763 [MainThread] - [CRITICAL] - [SnipsNlu] No NLU engine found, cannot start
NoneType: None
2020-03-02 19:46:47,766 [MainThread] - [INFO] - [ProjectAliceObject] Shutting down Project Alice
2020-03-02 19:46:47,768 [MainThread] - [INFO] - [ASR] Stopping Google ASR
2020-03-02 19:46:47,770 [MainThread] - [INFO] - [Manager] Stopping TTSManager
2020-03-02 19:46:47,773 [MainThread] - [INFO] - [Manager] Stopping ProtectedIntentManager
2020-03-02 19:46:47,775 [MainThread] - [INFO] - [Manager] Stopping ThreadManager
2020-03-02 19:46:48,781 [MainThread] - [INFO] - [Manager] Stopping TimeManager
2020-03-02 19:46:48,786 [MainThread] - [INFO] - [Manager] Stopping DialogSessionManager
2020-03-02 19:46:48,792 [MainThread] - [INFO] - [Manager] Stopping MultiIntentManager
2020-03-02 19:46:48,797 [MainThread] - [INFO] - [Manager] Stopping TelemetryManager
2020-03-02 19:46:48,803 [MainThread] - [INFO] - [Manager] Stopping DeviceManager
2020-03-02 19:46:48,808 [MainThread] - [INFO] - [DeviceManager] Stopped broadcasting for new devices
2020-03-02 19:46:48,816 [MainThread] - [INFO] - [Manager] Stopping WakewordManager
2020-03-02 19:46:49,822 [MainThread] - [INFO] - [Manager] Stopping SnipsWatchManager
2020-03-02 19:46:49,828 [MainThread] - [INFO] - [Manager] Stopping SkillStoreManager
2020-03-02 19:46:49,965 [MainThread] - [INFO] - [Manager] Starting NodeRedManager
2020-03-02 19:46:50,360 [MainThread] - [INFO] - [main] - Started Project Alice in 10.66 seconds
2020-03-02 19:46:50,362 [MainThread] - [INFO] - [main] Shutting down Project Alice
2020-03-02 19:46:50,364 [MainThread] - [INFO] - [ASR] Stopping Google ASR
2020-03-02 19:46:50,367 [MainThread] - [INFO] - [Manager] Stopping TTSManager
2020-03-02 19:46:50,371 [MainThread] - [INFO] - [Manager] Stopping ProtectedIntentManager
2020-03-02 19:46:50,374 [MainThread] - [INFO] - [Manager] Stopping ThreadManager
2020-03-02 19:46:50,379 [MainThread] - [INFO] - [Manager] Stopping TimeManager
2020-03-02 19:46:50,382 [MainThread] - [INFO] - [Manager] Stopping DialogSessionManager
2020-03-02 19:46:50,386 [MainThread] - [INFO] - [Manager] Stopping MultiIntentManager
2020-03-02 19:46:50,389 [MainThread] - [INFO] - [Manager] Stopping TelemetryManager
2020-03-02 19:46:50,392 [MainThread] - [INFO] - [Manager] Stopping DeviceManager
2020-03-02 19:46:50,394 [MainThread] - [INFO] - [DeviceManager] Stopped broadcasting for new devices
2020-03-02 19:46:50,399 [MainThread] - [INFO] - [Manager] Stopping WakewordManager
2020-03-02 19:46:51,401 [MainThread] - [INFO] - [Manager] Stopping SnipsWatchManager
2020-03-02 19:46:51,403 [MainThread] - [INFO] - [Manager] Stopping SkillStoreManager
2020-03-02 19:46:51,405 [MainThread] - [INFO] - [Manager] Stopping ConfigManager
2020-03-02 19:46:51,407 [MainThread] - [INFO] - [Manager] Stopping LanguageManager
2020-03-02 19:46:51,409 [MainThread] - [INFO] - [Manager] Stopping TalkManager
2020-03-02 19:46:51,411 [MainThread] - [INFO] - [Manager] Stopping SnipsServicesManager
2020-03-02 19:46:51,503 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-hotword stop'ed
2020-03-02 19:46:51,595 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-dialogue stop'ed
2020-03-02 19:46:51,708 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-audio-server stop'ed
2020-03-02 19:46:51,710 [MainThread] - [INFO] - [Manager] Stopping DatabaseManager
2020-03-02 19:46:51,712 [MainThread] - [INFO] - [Manager] Stopping UserManager
2020-03-02 19:46:51,713 [MainThread] - [INFO] - [Manager] Stopping MqttManager
2020-03-02 19:46:52,156 [MainThread] - [INFO] - [Manager] Stopping SkillManager
2020-03-02 19:46:52,159 [MainThread] - [INFO] - [SkillManager] - AliceCore stopped!
2020-03-02 19:46:52,161 [MainThread] - [INFO] - [SkillManager] - ContextSensitive stopped!
2020-03-02 19:46:52,163 [MainThread] - [INFO] - [SkillManager] - DateDayTimeYear stopped!
2020-03-02 19:46:52,165 [MainThread] - [INFO] - [SkillManager] - IcanhazdadjokeDotCom stopped!
2020-03-02 19:46:52,168 [MainThread] - [INFO] - [SkillManager] - RedQueen stopped!
2020-03-02 19:46:52,170 [MainThread] - [INFO] - [SkillManager] - Speedtest stopped!
2020-03-02 19:46:52,172 [MainThread] - [INFO] - [SkillManager] - Telemetry stopped!
2020-03-02 19:46:52,174 [MainThread] - [INFO] - [SkillManager] - Wikipedia stopped!
2020-03-02 19:46:52,176 [MainThread] - [INFO] - [Manager] Stopping DialogTemplateManager
2020-03-02 19:46:52,178 [MainThread] - [INFO] - [Manager] Stopping SnipsAssistantManager
2020-03-02 19:46:52,180 [MainThread] - [INFO] - [Manager] Stopping NluManager
2020-03-02 19:46:52,182 [MainThread] - [INFO] - [NluEngine] Stopping Snips NLU
2020-03-02 19:46:52,279 [MainThread] - [INFO] - [SnipsServicesManager] Service snips-nlu stop'ed
2020-03-02 19:46:52,281 [MainThread] - [INFO] - [Manager] Stopping InternetManager
2020-03-02 19:46:52,283 [MainThread] - [INFO] - [Manager] Stopping NodeRedManager
```

**Comment by Psychokiller1888** [comment]
Can you please give me the result of:

```
sudo systemctl stop ProjectAlice
cd ~/ProjectAlice
./venv/bin/snips-nlu /tmp/snipsNluDataset.json /tmp/snipsNLU
```

**Comment by hipitihop** [comment]
@Psychokiller1888 Probably not what you expected, sorry

```
pi@ProjectAlice:~/ProjectAlice $ ./venv/bin/snips-nlu /tmp/snipsNluDataset.json /tmp/snipsNLU
usage: python -m snips_nlu [-h] [-v] command [options ...] ...
python -m snips_nlu: error: argument command [options ...]: invalid choice: '/tmp/snipsNluDataset.json' (choose from 'generate-dataset', 'train', 'parse', 'download', 'download-all-languages', 'download-entity', 'download-language-entities', 'link', 'cross-val-metrics', 'train-test-metrics', 'version', 'model-version')
```

**Comment by Psychokiller1888** [comment]
Sry...

`./venv/bin/snips-nlu train /tmp/snipsNluDataset.json /tmp/snipsNLU`

**Comment by hipitihop** [comment]
@Psychokiller1888 np.. let me know if you need more then what spills in the term

```bash
~/ProjectAlice $ ./venv/bin/snips-nlu train /tmp/snipsNluDataset.json /tmp/snipsNLU
Create and train the engine...
Persisting the engine...
Saved the trained engine to /tmp/snipsNLU
```

**Comment by Psychokiller1888** [comment]
Yeah, that's a working nlu training. Well, updating the skill did fix this, closing the issue
