### ISSUE TITLE
[BUG] skill update failed

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#211]
Automatic skill update failed on RedQueen Skill. 
Left ledControl twinkling red lights which seems like a good indicator of there being issue during update.

Version 1.0.0-a6

```bash
2020-03-04 08:15:00,201 [Thread-62780] - [INFO] - [ThreadManager] Cleaned 1 dead timers
2020-03-04 08:30:00,544 [Thread-63854] - [INFO] - [ThreadManager] Cleaned 1 dead timers
2020-03-04 08:45:00,753 [Thread-64953] - [INFO] - [ThreadManager] Cleaned 0 dead timers
2020-03-04 09:00:00,269 [Thread-66307] - [INFO] - [ThreadManager] Cleaned 0 dead timers
2020-03-04 09:00:00,891 [Thread-62783] - [INFO] - [SkillManager] Checking for skill updates
2020-03-04 09:00:00,898 [Thread-62783] - [INFO] - [SkillManager] ✔ Telemetry - Version 1.1.2 in master
2020-03-04 09:00:00,907 [Thread-62783] - [INFO] - [SkillManager] ✔ BringShoppingList - Version 1.0.17 in master
2020-03-04 09:00:00,912 [Thread-62783] - [INFO] - [SkillManager] ✔ DateDayTimeYear - Version 1.0.23 in master
2020-03-04 09:00:00,917 [Thread-62783] - [INFO] - [SkillManager] ✔ IcanhazdadjokeDotCom - Version 1.0.23 in master
2020-03-04 09:00:00,922 [Thread-62783] - [INFO] - [SkillManager] ✔ Speedtest - Version 1.1.2 in master
2020-03-04 09:00:00,927 [Thread-62783] - [INFO] - [SkillManager] ✔ ContextSensitive - Version 1.0.16 in master
2020-03-04 09:00:00,932 [Thread-62783] - [INFO] - [SkillManager] ❌ AliceCore - Version 1.0.51 < 1.0.53 in master
2020-03-04 09:00:01,579 [Thread-62783] - [INFO] - [SkillManager] ✔ Speller - Version 1.1.2 in master
2020-03-04 09:00:01,585 [Thread-62783] - [INFO] - [SkillManager] ❌ RedQueen - Version 1.0.20 < 1.0.21 in master
2020-03-04 09:00:02,032 [Thread-62783] - [INFO] - [SkillManager] ✔ TextInputWidget - Version 0.1.1 in master
2020-03-04 09:00:02,034 [Thread-62783] - [INFO] - [SkillManager] ✔ Wikipedia - Version 1.1.3 in master
2020-03-04 09:00:02,036 [Thread-62783] - [INFO] - [SkillManager] Found 2 skill update(s)
2020-03-04 09:00:02,038 [Thread-62783] - [INFO] - [AliceCore] Checking Project Alice updates
2020-03-04 09:00:02,459 [Thread-68464] - [INFO] - [SkillManager] Found 2 install ticket(s)
2020-03-04 09:00:02,465 [Thread-68464] - [INFO] - [SkillManager] Now taking care of skill RedQueen
2020-03-04 09:00:02,470 [Thread-68464] - [WARNING] - [SkillManager] Skill "RedQueen" needs updating
2020-03-04 09:00:02,632 [Thread-62783] - [INFO] - [AliceCore] Checking on "1.0.0-a6" update channel
2020-03-04 09:00:04,717 [Thread-68464] - [INFO] - [SkillManager] Skill successfully downloaded
2020-03-04 09:00:04,721 [Thread-68464] - [ERROR] - [SkillManager] Failed installing skill "RedQueen": [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/RedQueen.install'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 495, in _installSkills
    self._installSkill(res)
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 547, in _installSkill
    installFile = json.loads(res.read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/RedQueen.install'
2020-03-04 09:00:04,727 [Thread-68464] - [ERROR] - [SkillManager] Error installing skill: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/RedQueen.install'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 406, in _checkForSkillInstall
    skillsToBoot = self._installSkills(files)
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 495, in _installSkills
    self._installSkill(res)
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 547, in _installSkill
    installFile = json.loads(res.read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/RedQueen.install'
2020-03-04 09:15:00,751 [Thread-68493] - [INFO] - [ThreadManager] Cleaned 0 dead timers
```

Update: Normal alice restart clears things and she works again.

**Comment by hipitihop** [comment]
And another auto update, this time on AliceCore
```bash
2020-03-04 17:00:00,997 [Thread-5025] - [INFO] - [SkillManager] Checking for skill updates
2020-03-04 17:00:01,002 [Thread-5025] - [INFO] - [SkillManager] ✔ BringShoppingList - Version 1.0.17 in master
2020-03-04 17:00:01,008 [Thread-5025] - [INFO] - [SkillManager] ✔ DateDayTimeYear - Version 1.0.23 in master
2020-03-04 17:00:01,010 [Thread-5025] - [INFO] - [SkillManager] ✔ IcanhazdadjokeDotCom - Version 1.0.23 in master
2020-03-04 17:00:01,012 [Thread-5025] - [INFO] - [SkillManager] ✔ Speedtest - Version 1.1.2 in master
2020-03-04 17:00:01,014 [Thread-5025] - [INFO] - [SkillManager] ✔ ContextSensitive - Version 1.0.16 in master
2020-03-04 17:00:01,016 [Thread-5025] - [INFO] - [SkillManager] ✔ Telemetry - Version 1.1.2 in master
2020-03-04 17:00:01,018 [Thread-5025] - [INFO] - [SkillManager] ✔ AliceCore - Version 1.0.53 in master
2020-03-04 17:00:01,020 [Thread-5025] - [INFO] - [SkillManager] ✔ Speller - Version 1.1.2 in master
2020-03-04 17:00:01,024 [Thread-5025] - [INFO] - [SkillManager] ✔ RedQueen - Version 1.0.21 in master
2020-03-04 17:00:01,028 [Thread-5025] - [INFO] - [SkillManager] ✔ TextInputWidget - Version 0.1.1 in master
2020-03-04 17:00:01,030 [Thread-5025] - [INFO] - [SkillManager] ✔ Wikipedia - Version 1.1.3 in master
2020-03-04 17:00:01,033 [Thread-5025] - [INFO] - [SkillManager] Found 0 skill update(s)
2020-03-04 17:00:01,036 [Thread-5025] - [INFO] - [AliceCore] Checking Project Alice updates
2020-03-04 17:00:01,437 [Thread-5025] - [INFO] - [AliceCore] Checking on "1.0.0-a6" update channel
2020-03-04 17:00:02,879 [Thread-10050] - [INFO] - [SkillManager] Found 5 install ticket(s)
2020-03-04 17:00:02,886 [Thread-10050] - [INFO] - [SkillManager] Now taking care of skill ContextSensitive
2020-03-04 17:00:02,890 [Thread-10050] - [WARNING] - [SkillManager] Skill "ContextSensitive" is already installed, skipping
2020-03-04 17:00:03,008 [Thread-10050] - [INFO] - [SkillManager] Now taking care of skill Telemetry
2020-03-04 17:00:03,015 [Thread-10050] - [WARNING] - [SkillManager] Skill "Telemetry" is already installed, skipping
2020-03-04 17:00:03,108 [Thread-10050] - [INFO] - [SkillManager] Now taking care of skill RedQueen
2020-03-04 17:00:03,113 [Thread-10050] - [WARNING] - [SkillManager] Skill "RedQueen" is already installed, skipping
2020-03-04 17:00:03,217 [Thread-10050] - [INFO] - [SkillManager] Now taking care of skill AliceCore
2020-03-04 17:00:03,220 [Thread-10050] - [ERROR] - [SkillManager] Failed installing skill "/home/pi/ProjectAlice/system/skillInstallTickets/AliceCore": [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/AliceCore.install'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 449, in _installSkills
    installFile = json.loads(res.read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/AliceCore.install'
2020-03-04 17:00:03,223 [Thread-10050] - [ERROR] - [SkillManager] Error installing skill: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/AliceCore.install'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 406, in _checkForSkillInstall
    skillsToBoot = self._installSkills(files)
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 449, in _installSkills
    installFile = json.loads(res.read_text())
  File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.7/pathlib.py", line 1186, in open
    opener=self._opener)
  File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/AliceCore.install'
```

**Comment by LazzaAU** [comment]
I had the same issue and created the file with 
`nano ~/ProjectAlice/system/skillInstallTickets/AliceCore.install`

then copied the raw file data from https://github.com/project-alice-assistant/ProjectAlice/blob/master/system/skillInstallTickets/AliceCore.install

and rebooted. Seemed to of fixed my issue but still left with no idea why it happened. Sorry can't be any more help than that :)

**Comment by LazzaAU** [comment]
I have a similar output. I can invoke it by doing a manual update from the admin panel 
(see timestamps in this first log shows 27 minutes and no acknowledgment the update is complete or in still progress )

>Mar 11 18:10:23 ProjectAlice python3[486]: [AdminView] Checking Project Alice updates
Mar 11 18:10:23 ProjectAlice python3[486]: [AdminView] Checking on "1.0.0-a6" update channel
Mar 11 18:15:00 ProjectAlice python3[486]: [ThreadManager] Cleaned 0 dead timers
Mar 11 18:17:01 ProjectAlice CRON[1515]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Mar 11 18:24:39 ProjectAlice systemd[1]: Starting Cleanup of Temporary Directories...
Mar 11 18:24:39 ProjectAlice systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
Mar 11 18:24:39 ProjectAlice systemd[1]: Started Cleanup of Temporary Directories.
Mar 11 18:37:00 ProjectAlice python3[486]: [ThreadManager] Cleaned 0 dead timers

Alice knows there is update tickets
>[SkillManager] Checking for skill updates
[SkillManager] ✔ DateDayTimeYear - Version 1.0.24 in alpha
[SkillManager] ❌ ContextSensitive - Version 1.0.16 < 1.0.17 in alpha
[SkillManager] ❌ AliceCore - Version 1.0.56 < 1.0.58 in alpha
[SkillManager] ❌ RedQueen - Version 1.0.21 < 1.0.22 in alpha
[SkillManager] ✔ TextInputWidget - Version 0.1.1 in alpha
[SkillManager] ❌ SpeechVisualizer - Version 0.0.7 < 1.0.1 in alpha
[SkillManager] ✔ Tasmota - Version 1.1.2 in alpha
[SkillManager] Found 4 skill update(s)

**Things i've noticed**
If watching the log files not much happens as per above. So restarting Alice brings up the following errors on start up. Which i believe is likely to be normal due to a incomplete update process. ?? Restarting Alice twice and she fixes these errors but updates still show outstanding.

>Mar 11 18:39:32 ProjectAlice python3[486]: [AdminView] Checking Project Alice updates
Mar 11 18:39:33 ProjectAlice python3[486]: [AdminView] Checking on "1.0.0-a6" update channel
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Found 5 install ticket(s)
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Now taking care of skill ContextSensitive
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Skill "ContextSensitive" is already installed, skipping
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Now taking care of skill Telemetry
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Skill "Telemetry" does not comply to "activeManager" condition, required "['TelemetryManager']"
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Now taking care of skill RedQueen
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Skill "RedQueen" is already installed, skipping
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Now taking care of skill AliceCore
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Skill "AliceCore" is already installed, skipping
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Now taking care of skill DateDayTimeYear
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Failed installing skill "/home/pi/ProjectAlice/system/skillInstallTickets/DateDayTimeYear": [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/DateDayTimeYear.install'
Mar 11 18:39:35 ProjectAlice python3[486]: Traceback (most recent call last):
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 453, in _installSkills
Mar 11 18:39:35 ProjectAlice python3[486]:     installFile = json.loads(res.read_text())
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
Mar 11 18:39:35 ProjectAlice python3[486]:     with self.open(mode='r', encoding=encoding, errors=errors) as f:
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1186, in open
Mar 11 18:39:35 ProjectAlice python3[486]:     opener=self._opener)
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
Mar 11 18:39:35 ProjectAlice python3[486]:     return self._accessor.open(self, flags, mode)
Mar 11 18:39:35 ProjectAlice python3[486]: FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/DateDayTimeYear.install'
Mar 11 18:39:35 ProjectAlice python3[486]: [SkillManager] Error installing skill: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/DateDayTimeYear.install'
Mar 11 18:39:35 ProjectAlice python3[486]: Traceback (most recent call last):
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 410, in _checkForSkillInstall
Mar 11 18:39:35 ProjectAlice python3[486]:     skillsToBoot = self._installSkills(files)
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 453, in _installSkills
Mar 11 18:39:35 ProjectAlice python3[486]:     installFile = json.loads(res.read_text())
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1199, in read_text
Mar 11 18:39:35 ProjectAlice python3[486]:     with self.open(mode='r', encoding=encoding, errors=errors) as f:
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1186, in open
Mar 11 18:39:35 ProjectAlice python3[486]:     opener=self._opener)
Mar 11 18:39:35 ProjectAlice python3[486]:   File "/usr/lib/python3.7/pathlib.py", line 1039, in _opener
Mar 11 18:39:35 ProjectAlice python3[486]:     return self._accessor.open(self, flags, mode)
Mar 11 18:39:35 ProjectAlice python3[486]: FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/ProjectAlice/system/skillInstallTickets/DateDayTimeYear.install'
Mar 11 18:45:00 ProjectAlice python3[486]: [ThreadManager] Cleaned 0 dead timers

**Additional errors**
Under the same circumstances ( clicking update button and it hanging) i also get the below errors which again i believe is normal due to a incomplete update ??. but documenting it for reference :)

> ERROR:snips_nlu: assistant.json file not found in assistant at path "/home/pi/ProjectAlice/assistant"

and then followed by multiple NLU engine errors as per below . However because at this point Alice is also doing training among the errors, the user needs to wait until training is finished or she doesnt recreate the assistant.json file for the next boot when she seems to correct all the issues on her own (apart from the actual update of skills)

> ERROR:snips_nlu: couldn't find any NLU engine

A full log example can be found here if it helps https://pastebin.com/GWNiMv3e .

**Comment by LazzaAU** [comment]
Ticking auto update for both ASR and skills allows Alice to update the skills successfully. So for me the bug is 

With autoupdate in the admin panel is "unticked" for both ASR and skills. then clicking the "update button" in admin panel i get the above issues.. enabling Auto update for both items and restart seems to fix the updating issues

**Comment by LazzaAU** [comment]
I appear to have the same errors.
