### ISSUE TITLE
[BUG] using admin util "Tune Wakeword"

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#224]
Failure when using the "Tune Wakeword" admin util.

```bash
2020-03-15 11:55:31,289 [Thread-1] - [WARNING] - [SkillManager] - Failed to broadcast event onUserCancel to RedQueen: 'NoneType' object is not subscriptable
2020-03-15 12:00:00,580 [Thread-6153] - [INFO] - [SkillManager] Checking for skill updates
2020-03-15 12:00:00,585 [Thread-6153] - [INFO] - [SkillManager] ✔ IgnoreWakeword - Version 0.0.1 in alpha
2020-03-15 12:00:00,587 [Thread-6153] - [INFO] - [SkillManager] ✔ Userfacts - Version 1.0.2 in alpha
2020-03-15 12:00:00,589 [Thread-6153] - [INFO] - [SkillManager] ✔ BringShoppingList - Version 1.0.18 in alpha
2020-03-15 12:00:00,591 [Thread-6153] - [INFO] - [SkillManager] ✔ DateDayTimeYear - Version 1.0.24 in alpha
2020-03-15 12:00:00,593 [Thread-6153] - [INFO] - [SkillManager] ✔ IcanhazdadjokeDotCom - Version 1.0.23 in alpha
2020-03-15 12:00:00,595 [Thread-6153] - [INFO] - [SkillManager] ✔ Speedtest - Version 1.1.2 in alpha
2020-03-15 12:00:00,597 [Thread-6153] - [INFO] - [SkillManager] ✔ ContextSensitive - Version 1.0.17 in alpha
2020-03-15 12:00:00,599 [Thread-6153] - [INFO] - [SkillManager] ✔ Telemetry - Version 1.1.4 in alpha
2020-03-15 12:00:00,601 [Thread-6153] - [INFO] - [SkillManager] ✔ AliceCore - Version 1.0.58 in alpha
2020-03-15 12:00:00,603 [Thread-6153] - [INFO] - [SkillManager] ✔ Speller - Version 1.1.2 in alpha
2020-03-15 12:00:00,605 [Thread-6153] - [INFO] - [SkillManager] ✔ RedQueen - Version 1.0.22 in alpha
2020-03-15 12:00:00,607 [Thread-6153] - [INFO] - [SkillManager] ✔ TextInputWidget - Version 0.1.1 in alpha
2020-03-15 12:00:00,609 [Thread-6153] - [INFO] - [SkillManager] ✔ SpeechVisualizer - Version 1.0.1 in alpha
2020-03-15 12:00:00,611 [Thread-6153] - [INFO] - [SkillManager] Found 0 skill update(s)
2020-03-15 12:00:00,616 [Thread-6153] - [INFO] - [AliceCore] Checking Project Alice updates
2020-03-15 12:00:00,655 [Thread-13169] - [WARNING] - [SkillManager] - Failed to broadcast event onFiveMinute to RedQueen: 'NoneType' object is not subscriptable
2020-03-15 12:00:00,979 [Thread-11897] - [INFO] - [ThreadManager] Cleaned 2 dead timers
2020-03-15 12:00:01,022 [Thread-6153] - [INFO] - [AliceCore] Checking on "1.0.0-a6" update channel
2020-03-15 12:00:03,199 [Thread-11897] - [WARNING] - [SkillManager] - Failed to broadcast event onQuarterHour to RedQueen: 'NoneType' object is not subscriptable
2020-03-15 12:01:45,966 [Thread-1] - [WARNING] - [SkillManager] - Failed to broadcast event onUserCancel to RedQueen: 'NoneType' object is not subscriptable
2020-03-15 12:02:42,800 [Thread-1] - [ERROR] - [MqttManager] Error in onMessage: 'username'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 224, in onMqttMessage
    consumed = skill.onDispatchMessage(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 404, in onDispatchMessage
    return function(session=session)
  File "/home/pi/ProjectAlice/skills/AliceCore/AliceCore.py", line 509, in doWakewordTuning
    username = session.customData['username']
KeyError: 'username'
```

**Steps:**
- logged into web admin, chose utils and "Tune Wakeword"
- Alice asked for which user
- I responded with my user name
- Alice confirmed the user name
- I confirmed it was correct.
- Alice asked 1 or 2, I responded 2
She pinged, leds went out and then above was seen in logs.

**Unqualified Theory**
The timing in the log seems to suggest she may still have been part through an automatic update ?

**Comment by hipitihop** [comment]
@Psychokiller1888 I have since retried these steps and everything worked as expected. Closing for now.

**Comment by Psychokiller1888** [comment]
Oh, yes, forgot to write here, this was fixed
