### ISSUE TITLE
[BUG} - incomplete session after using dialogview

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#431]
**ISSUE** 

When using for example "reminder" skill via the webInterface the exisiting session gets replaced with userRandomeAnswer session when trying to add a message.

**TO REPLICATE**

In dialog View
- You type ... add a timer for 1 minute
- Alice asks you " what message would you like to call this timer"
- You type .... test message (or what ever)
- the following error will be observed

```
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 245, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 463, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 262, in processTheSpecifiedTime
    self.processAndStoreReminder(session, secs)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 279, in processAndStoreReminder
    timeStampForDb = self.createEpochTimeStamp(secs)
  File "/home/pi/ProjectAlice/skills/Reminder/Reminder.py", line 363, in createEpochTimeStamp
    timeStampForDatabase = datetime.now() + timedelta(seconds=seconds)
TypeError: unsupported type for timedelta seconds component: str
```

**NOTE**

The skill works as expected when using "voice" commands. This only occurs if using dialog View

**STEPS TAKEN ALREADY**
I've traced it back as far as i can but it appears the initial session with the timer information is replaced with the userRandomAnswer session (rather than appended to it) prior to  ```File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 245, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)``` which i feel starts getting into ```_handle_on_message``` or further which i'm lost at that point.
    
  **LOGS**

https://paste.ubuntu.com/p/ysD6vN6rd3/

**Comment by Psychokiller1888** [comment]
Nope, that's because the `seconds` variable is of type str when coming from the interface. Add a cast to int for those cases

**Comment by philipp2310** [comment]
Adding a cast won't be enough - the variable is an empty string in that case - the seconds value is not existing anymore (either lost between the api calls or was never saved)
