### ISSUE TITLE
Alice don't recreate the symbolic link assistent to point the right place at language change.

### ISSUE THREAD

**Issue by poulsp** [project-alice-assistant/ProjectAlice#448]
As stated in the title.

**Comment by poulsp** [comment]
I will test it as as soon as possible and then close this issue.

**Comment by poulsp** [comment]
Could not get it work.

[DialogTemplateManager]   Building dialog templates cache
[SnipsNlu]                Preparing NLU training file
[SnipsNlu]                Training Snips NLU
[SnipsNlu]                Generated dataset for training
[SnipsNlu]                Begin training...
[SnipsNlu] Error while training Snips NLU: Traceback (most recent call last):
  File "./venv/bin/snips-nlu", line 8, in <module>
    sys.exit(main())
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/init.py", line 52, in main
    args.func(args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/training.py", line 26, in _train
    args_namespace.random_seed)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/training.py", line 56, in train
    engine = SnipsNLUEngine(config, random_state=random_state).fit(dataset)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/common/log_utils.py", line 30, in wrapped
    res = fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/nlu_engine/nlu_engine.py", line 104, in fit
    self.load_resources_if_needed(dataset[LANGUAGE])
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/pipeline/processing_unit.py", line 134, in load_resources_if_needed
    self.resources = load_resources(language, required_resources)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/resources.py", line 47, in load_resources
    .format(r=name))
snips_nlu.resources.MissingResource: Language resource 'de' not found. This may be solved by running 'python -m snips_nlu download de'
NoneType: None
[SnipsNlu]                Snips NLU training failed
NoneType: None
[SnipsNlu]                No NLU engine found, cannot start
NoneType: None
[Project Alice]           Shutting down
Error while shutting down manager unknownManager: 'MqttManager'

After `python -m snips_nlu download de`

```
[SnipsNlu]                Begin training...
[SnipsNlu]                Snips NLU trained in 12.25 seconds
[SnipsNlu]                Stopping Snips NLU
[SubprocessManager]       Tried terminating the subprocess SnipsNLU, but it was not found
NoneType: None
[SnipsNlu]                Starting Snips NLU
[SubprocessManager]       Starting the subprocess SnipsNLU
[ThreadManager]           Started new thread checkHeartbeats, thread count: 11
[ThreadManager]           Started new thread heartBeatThread-1622634419, thread count: 11
[SnipsNlu]                Starting Snips NLU
[SubprocessManager]       Tried adding the subprocess SnipsNLU twice

But I must also delete ~/ProjectAlice/assistant manually for it to work.
