### ISSUE TITLE
Amazon TTS should specify engine based on voice type configured i.e. 'standard' or 'neural'

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#449]
Amazon Polly supports both "standard" and "neural" voices and in turn the corresponding engine should be correctly specified in the request [see Polly API ](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/polly.html#Polly.Client.synthesize_speech)

At the moment this is hardcoded to `'standard'`
https://github.com/project-alice-assistant/ProjectAlice/blob/137543b3e3bac4a7e0cb184e10058d875d764650/core/voice/model/AmazonTts.py#L277

Suggestion:
specify the engine based on the configured voices property `'neural': False`

See [Alice configured voices:](https://github.com/project-alice-assistant/ProjectAlice/blob/137543b3e3bac4a7e0cb184e10058d875d764650/core/voice/model/AmazonTts.py#L34) which should probably also be updated to [latest list of voices](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html) at the same time.

Some consideration also needs to be given to the `TextType` param as we annotate utternace with auto breath SSML etc.

**Comment by Psychokiller1888** [comment]
I just added the support, can you test, I don't have any working Alice unit at work sry

**Comment by hipitihop** [comment]
@Psychokiller1888 notice the engine should be a string of either 'standard' or 'neural' and `self._neuralVoice` returns a bool. So this understandably fails as per below. Also, if the engine type is not a prop of all TTS and only Amazon, then perhaps `_neuralVoice` should be in the AmazonTts ?

```
2021-05-27T00:14:04.189787894Z [MqttManager] Caught exception in user defined callback function intentSay: Parameter validation failed:
2021-05-27T00:14:04.189802812Z Invalid type for parameter Engine, value: True, type: <class 'bool'>, valid types: <class 'str'>
2021-05-27T00:15:00.875839327Z Traceback (most recent call last):
2021-05-27T00:15:00.875868172Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3429, in _handle_on_message
2021-05-27T00:15:00.875875025Z     callback(self, self._userdata, message)
2021-05-27T00:15:00.875880566Z   File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 492, in intentSay
2021-05-27T00:15:00.875886597Z     self.broadcast(method=constants.EVENT_SAY, exceptions=[self.name], propagateToSkills=True, session=session)
2021-05-27T00:15:00.875893039Z   File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 132, in broadcast
2021-05-27T00:15:00.875898880Z     func(**kwargs)
2021-05-27T00:15:00.875904310Z   File "/home/pi/ProjectAlice/core/voice/TTSManager.py", line 157, in onSay
2021-05-27T00:15:00.875909691Z     self._tts.onSay(session)
2021-05-27T00:15:00.875913428Z   File "/home/pi/ProjectAlice/core/voice/model/AmazonTts.py", line 303, in onSay
2021-05-27T00:15:00.875917535Z     VoiceId=self._voice.title()
2021-05-27T00:15:00.875921533Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
2021-05-27T00:15:00.875925340Z     endpoint_url, is_secure):
2021-05-27T00:15:00.875930149Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/client.py", line 678, in _make_api_call
2021-05-27T00:15:00.875936381Z     api_params = first_non_none_response(responses, default=api_params)
2021-05-27T00:15:00.875943565Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/client.py", line 726, in _convert_to_request_dict
2021-05-27T00:15:00.875949276Z     paginator_config=paginator_config,
2021-05-27T00:15:00.875954505Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/validate.py", line 293, in serialize_to_request
2021-05-27T00:15:00.875970315Z     if input_shape is not None:
2021-05-27T00:15:00.875973942Z botocore.exceptions.ParamValidationError: Parameter validation failed:
2021-05-27T00:15:00.875977188Z Invalid type for parameter Engine, value: True, type: <class 'bool'>, valid types: <class 'str'>```

**Comment by hipitihop** [comment]
@Psychokiller1888 also note there is an issue with the TextYTpe as mentioned in original issue description. If we specify `neural` engine, then we can't specify `'ssml'` for the TextType, it must be '`text'` or polly complains, but in turn when it is text, the uttererance/text includes the ssml markup like breath etc, and is just read out. I'm not sure where the extra markup is coming from at the moment. Looks like the neural voices don't support the markup, which is a trade off to support them.

Thoughts?
