### ISSUE TITLE
AmazonTTS lags around 60 seconds after period of inactivity

### ISSUE THREAD

**Issue by hipitihop** [project-alice-assistant/ProjectAlice#453]
**Problem:**
After a period of Alice inactivity, the first un-cached TTS response from Amazon Polly takes 60 seconds. Subsequent interactions are normal until the next period of inactivity, at which point another 60 sec wait is incurred before Alice gets the downloaded TTS and can then play the audio.

**Cause:**
The library used for interacting with Amazon is [boto3](https://github.com/boto/boto3) which in it's default configuration causes this the lag waiting for the standard timeout.
Thanks to this HA PR for explanation and fix: https://github.com/home-assistant/core/pull/44185

**Action:**
Upgrade to latest boto3 library and implement pool and timouts as per above PR

**Comment by hipitihop** [comment]
Example of boto3 timeout/retry with new settings and logging turned on, now only takes a total of about 6 sec.

So whenever the pooled connection does die, it now only waits 5 sec for timeout. When connection is not stale, response is normal and even faster. So on my machine, the worst case scenario is around 6 seconds. YMMV obviously depending on the length of text being converted, your host, network, internet etc)

```
2021-05-29T02:49:45.056533819Z [AmazonTts]               Downloading file
..... Boto3 does it's stuff .....
2021-05-29T02:49:51.204315538Z [AmazonTts]               Downloaded speech file
```
**Full log**
```
2021-05-29T02:49:44.989675920Z [SkillManager]            The intent "GetTime" was consumed by DateDayTimeYear
2021-05-29T02:49:44.989769006Z 2021-05-29 12:49:44,989 ProjectAlice [DEBUG] [SkillManager]            The intent "GetTime" was consumed by DateDayTimeYear
2021-05-29T02:49:45.056533819Z [AmazonTts]               Downloading file 743139b92d54452d8cb057875a2fafaa
2021-05-29T02:49:45.056705123Z 2021-05-29 12:49:45,056 ProjectAlice [DEBUG] [AmazonTts]               Downloading file **743139b92d54452d8cb057875a2fafaa**
2021-05-29T02:49:45.057096053Z 2021-05-29 12:49:45,056 botocore.hooks [DEBUG] Event before-parameter-build.polly.SynthesizeSpeech: calling handler <function generate_idempotent_uuid at 0x7fcbb55d37a0>
2021-05-29T02:49:45.057474891Z 2021-05-29 12:49:45,057 botocore.hooks [DEBUG] Event before-call.polly.SynthesizeSpeech: calling handler <function inject_api_version_header_if_needed at 0x7fcbb55dc050>
2021-05-29T02:49:45.057581653Z 2021-05-29 12:49:45,057 botocore.endpoint [DEBUG] Making request for OperationModel(name=SynthesizeSpeech) with params: {'url_path': '/v1/speech', 'query_string': {}, 'method': 'POST', 'headers': {'User-Agent': 'Boto3/1.17.84 Python/3.7.7 Linux/5.8.0-53-generic Botocore/1.20.84'}, 'body': b'{"Engine": "standard", "LanguageCode": "en-GB", "OutputFormat": "mp3", "SampleRate": "16000", "Text": "<speak><amazon:auto-breaths>It is 12 49</amazon:auto-breaths></speak>", "TextType": "ssml", "VoiceId": "Amy"}', 'url': 'https://polly.us-west-1.amazonaws.com/v1/speech', 'context': {'client_region': 'us-west-1', 'client_config': <botocore.config.Config object at 0x7fcc069dffd0>, 'has_streaming_input': False, 'auth_type': None}}
2021-05-29T02:49:45.057766052Z 2021-05-29 12:49:45,057 botocore.hooks [DEBUG] Event request-created.polly.SynthesizeSpeech: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fcc069dfed0>>
2021-05-29T02:49:45.057905977Z 2021-05-29 12:49:45,057 botocore.hooks [DEBUG] Event choose-signer.polly.SynthesizeSpeech: calling handler <function set_operation_specific_signer at 0x7fcbb55d3680>
2021-05-29T02:49:45.058251541Z 2021-05-29 12:49:45,058 botocore.auth [DEBUG] Calculating signature using v4 auth.
2021-05-29T02:49:45.058290265Z 2021-05-29 12:49:45,058 botocore.auth [DEBUG] CanonicalRequest:
2021-05-29T02:49:45.058300374Z POST
2021-05-29T02:49:45.058305553Z /v1/speech
2021-05-29T02:49:45.058310212Z 
2021-05-29T02:49:45.058314009Z host:polly.us-west-1.amazonaws.com
2021-05-29T02:49:45.058317977Z x-amz-date:20210529T024945Z
2021-05-29T02:49:45.058322195Z 
2021-05-29T02:49:45.058325842Z host;x-amz-date
2021-05-29T02:49:45.058329629Z deb6bdaac186922b25c1a60c656e28bb49526fdedcd9a69a813bb5bdeef5345a
2021-05-29T02:49:45.058349677Z 2021-05-29 12:49:45,058 botocore.auth [DEBUG] StringToSign:
2021-05-29T02:49:45.058367811Z AWS4-HMAC-SHA256
2021-05-29T02:49:45.058375185Z 20210529T024945Z
2021-05-29T02:49:45.058381648Z 20210529/us-west-1/polly/aws4_request
2021-05-29T02:49:45.058387769Z 7a1417f9cfad9325469af3b419dce9ba6a9f5d1dfe4269ac8a6bf9dc24abed07
2021-05-29T02:49:45.058466949Z 2021-05-29 12:49:45,058 botocore.auth [DEBUG] Signature:
2021-05-29T02:49:45.058476918Z dd9f1527b27077c499fea8972c46c837c5756603147f1ba74aa5a743c80fb185
2021-05-29T02:49:45.058620430Z 2021-05-29 12:49:45,058 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=True, method=POST, url=https://polly.us-west-1.amazonaws.com/v1/speech, headers={'User-Agent': b'Boto3/1.17.84 Python/3.7.7 Linux/5.8.0-53-generic Botocore/1.20.84', 'X-Amz-Date': b'20210529T024945Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=<mycreds>/20210529/us-west-1/polly/aws4_request, SignedHeaders=host;x-amz-date, Signature=<mysig>', 'Content-Length': '212'}>
2021-05-29T02:49:45.058898837Z 2021-05-29 12:49:45,058 botocore.httpsession [DEBUG] Certificate path: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/certifi/cacert.pem
2021-05-29T02:49:47.441952809Z 2021-05-29 12:49:47,441 urllib3.connectionpool [DEBUG] Starting new HTTPS connection (1): clients3.google.com:443
2021-05-29T02:49:47.604982778Z 2021-05-29 12:49:47,604 urllib3.connectionpool [DEBUG] https://clients3.google.com:443 "GET /generate_204 HTTP/1.1" 204 0
2021-05-29T02:49:50.065142070Z 2021-05-29 12:49:50,064 botocore.hooks [DEBUG] Event needs-retry.polly.SynthesizeSpeech: calling handler <botocore.retryhandler.RetryHandler object at 0x7fcc0698c310>
2021-05-29T02:49:50.067630793Z 2021-05-29 12:49:50,065 botocore.retryhandler [DEBUG] retry needed, retryable exception caught: Read timeout on endpoint URL: "https://polly.us-west-1.amazonaws.com/v1/speech"
2021-05-29T02:49:50.067644729Z Traceback (most recent call last):
2021-05-29T02:49:50.067648927Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
2021-05-29T02:49:50.067652944Z     six.raise_from(e, None)
2021-05-29T02:49:50.067656241Z   File "<string>", line 3, in raise_from
2021-05-29T02:49:50.067659908Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
2021-05-29T02:49:50.067677441Z     httplib_response = conn.getresponse()
2021-05-29T02:49:50.067682711Z   File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
2021-05-29T02:49:50.067688241Z     response.begin()
2021-05-29T02:49:50.067693010Z   File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
2021-05-29T02:49:50.067698541Z     version, status, reason = self._read_status()
2021-05-29T02:49:50.067702719Z   File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
2021-05-29T02:49:50.067706095Z     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2021-05-29T02:49:50.067709411Z   File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
2021-05-29T02:49:50.067712738Z     return self._sock.recv_into(b)
2021-05-29T02:49:50.067715854Z   File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
2021-05-29T02:49:50.067719140Z     return self.read(nbytes, buffer)
2021-05-29T02:49:50.067722276Z   File "/usr/local/lib/python3.7/ssl.py", line 929, in read
2021-05-29T02:49:50.067725762Z     return self._sslobj.read(len, buffer)
2021-05-29T02:49:50.067728878Z socket.timeout: The read operation timed out
2021-05-29T02:49:50.067732014Z 
2021-05-29T02:49:50.067735210Z During handling of the above exception, another exception occurred:
2021-05-29T02:49:50.067738526Z 
2021-05-29T02:49:50.067741532Z Traceback (most recent call last):
2021-05-29T02:49:50.067744688Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/httpsession.py", line 332, in send
2021-05-29T02:49:50.067748946Z     chunked=self._chunked(request.headers),
2021-05-29T02:49:50.067753725Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
2021-05-29T02:49:50.067758805Z     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
2021-05-29T02:49:50.067763684Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 386, in increment
2021-05-29T02:49:50.067768944Z     raise six.reraise(type(error), error, _stacktrace)
2021-05-29T02:49:50.067773924Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
2021-05-29T02:49:50.067779063Z     raise value
2021-05-29T02:49:50.067784744Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
2021-05-29T02:49:50.067789984Z     chunked=chunked,
2021-05-29T02:49:50.067794763Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 428, in _make_request
2021-05-29T02:49:50.067799893Z     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
2021-05-29T02:49:50.067804672Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
2021-05-29T02:49:50.067815442Z     self, url, "Read timed out. (read timeout=%s)" % timeout_value
2021-05-29T02:49:50.067819390Z urllib3.exceptions.ReadTimeoutError: AWSHTTPSConnectionPool(host='polly.us-west-1.amazonaws.com', port=443): Read timed out. (read timeout=5)
2021-05-29T02:49:50.067824479Z 
2021-05-29T02:49:50.067828968Z During handling of the above exception, another exception occurred:
2021-05-29T02:49:50.067833977Z 
2021-05-29T02:49:50.067837905Z Traceback (most recent call last):
2021-05-29T02:49:50.067841091Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 269, in _should_retry
2021-05-29T02:49:50.067844507Z     return self._checker(attempt_number, response, caught_exception)
2021-05-29T02:49:50.067847733Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 317, in __call__
2021-05-29T02:49:50.067851290Z     caught_exception)
2021-05-29T02:49:50.067854426Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 223, in __call__
2021-05-29T02:49:50.067857782Z     attempt_number, caught_exception)
2021-05-29T02:49:50.067860918Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
2021-05-29T02:49:50.067864405Z     raise caught_exception
2021-05-29T02:49:50.067867551Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/endpoint.py", line 200, in _do_get_response
2021-05-29T02:49:50.067871037Z     http_response = self._send(request)
2021-05-29T02:49:50.067874374Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/endpoint.py", line 269, in _send
2021-05-29T02:49:50.067877750Z     return self.http_session.send(request)
2021-05-29T02:49:50.067880926Z   File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/botocore/httpsession.py", line 358, in send
2021-05-29T02:49:50.067884353Z     raise ReadTimeoutError(endpoint_url=request.url, error=e)
2021-05-29T02:49:50.067889542Z botocore.exceptions.ReadTimeoutError: Read timeout on endpoint URL: "https://polly.us-west-1.amazonaws.com/v1/speech"
2021-05-29T02:49:50.067898038Z 2021-05-29 12:49:50,067 botocore.retryhandler [DEBUG] Retry needed, action of: 0.28668574833173976
2021-05-29T02:49:50.067932173Z 2021-05-29 12:49:50,067 botocore.endpoint [DEBUG] Response received to retry, sleeping for 0.28668574833173976 seconds
2021-05-29T02:49:50.355327690Z 2021-05-29 12:49:50,355 botocore.hooks [DEBUG] Event request-created.polly.SynthesizeSpeech: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fcc069dfed0>>
2021-05-29T02:49:50.355464859Z 2021-05-29 12:49:50,355 botocore.hooks [DEBUG] Event choose-signer.polly.SynthesizeSpeech: calling handler <function set_operation_specific_signer at 0x7fcbb55d3680>
2021-05-29T02:49:50.355958915Z 2021-05-29 12:49:50,355 botocore.auth [DEBUG] Calculating signature using v4 auth.
2021-05-29T02:49:50.356054837Z 2021-05-29 12:49:50,355 botocore.auth [DEBUG] CanonicalRequest:
2021-05-29T02:49:50.356072099Z POST
2021-05-29T02:49:50.356076207Z /v1/speech
2021-05-29T02:49:50.356079513Z 
2021-05-29T02:49:50.356082188Z host:polly.us-west-1.amazonaws.com
2021-05-29T02:49:50.356084783Z x-amz-date:20210529T024950Z
2021-05-29T02:49:50.356087629Z 
2021-05-29T02:49:50.356090083Z host;x-amz-date
2021-05-29T02:49:50.356092538Z deb6bdaac186922b25c1a60c656e28bb49526fdedcd9a69a813bb5bdeef5345a
2021-05-29T02:49:50.356186366Z 2021-05-29 12:49:50,356 botocore.auth [DEBUG] StringToSign:
2021-05-29T02:49:50.356249365Z AWS4-HMAC-SHA256
2021-05-29T02:49:50.356274032Z 20210529T024950Z
2021-05-29T02:49:50.356296023Z 20210529/us-west-1/polly/aws4_request
2021-05-29T02:49:50.356334546Z 4749cfdbc4b0d0109c416b7c070fec11dcbf2c60db278a038ed9b7491f4bcd08
2021-05-29T02:49:50.356361036Z 2021-05-29 12:49:50,356 botocore.auth [DEBUG] Signature:
2021-05-29T02:49:50.356386124Z 5ae8c58748cd5bf804b7c41aac1e46b43e52b3712036455432248bc12dcaa716
2021-05-29T02:49:50.356493818Z 2021-05-29 12:49:50,356 botocore.endpoint [DEBUG] Sending http request: <AWSPreparedRequest stream_output=True, method=POST, url=https://polly.us-west-1.amazonaws.com/v1/speech, headers={'User-Agent': b'Boto3/1.17.84 Python/3.7.7 Linux/5.8.0-53-generic Botocore/1.20.84', 'X-Amz-Date': b'20210529T024950Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential=<mycreds>/20210529/us-west-1/polly/aws4_request, SignedHeaders=host;x-amz-date, Signature=<mysig>', 'Content-Length': '212'}>
2021-05-29T02:49:50.356914203Z 2021-05-29 12:49:50,356 botocore.httpsession [DEBUG] Certificate path: /home/pi/ProjectAlice/venv/lib/python3.7/site-packages/certifi/cacert.pem
2021-05-29T02:49:50.357092331Z 2021-05-29 12:49:50,357 urllib3.connectionpool [DEBUG] Starting new HTTPS connection (2): polly.us-west-1.amazonaws.com:443
2021-05-29T02:49:51.185319884Z 2021-05-29 12:49:51,185 urllib3.connectionpool [DEBUG] https://polly.us-west-1.amazonaws.com:443 "POST /v1/speech HTTP/1.1" 200 None
2021-05-29T02:49:51.185555991Z 2021-05-29 12:49:51,185 botocore.parsers [DEBUG] Response headers: {'x-amzn-RequestId': 'd879e534-6242-43bc-8cf3-8954b0f668d6', 'x-amzn-RequestCharacters': '11', 'Content-Type': 'audio/mpeg', 'Transfer-Encoding': 'chunked', 'Date': 'Sat, 29 May 2021 02:49:50 GMT'}
2021-05-29T02:49:51.185611536Z 2021-05-29 12:49:51,185 botocore.parsers [DEBUG] Response body:
2021-05-29T02:49:51.185632616Z <botocore.response.StreamingBody object at 0x7fcc00c57850>
2021-05-29T02:49:51.185964334Z 2021-05-29 12:49:51,185 botocore.hooks [DEBUG] Event needs-retry.polly.SynthesizeSpeech: calling handler <botocore.retryhandler.RetryHandler object at 0x7fcc0698c310>
2021-05-29T02:49:51.186033034Z 2021-05-29 12:49:51,185 botocore.retryhandler [DEBUG] No retry needed.
2021-05-29T02:49:51.204315538Z [AmazonTts]               Downloaded speech file 743139b92d54452d8cb057875a2fafaa
2021-05-29T02:49:51.204505618Z 2021-05-29 12:49:51,203 ProjectAlice [DEBUG] [AmazonTts]               Downloaded speech file **743139b92d54452d8cb057875a2fafaa**
```
