### ISSUE TITLE
[BUG] Telemetry reporting error

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#488]
**Describe the bug**
Asking Alice " what's the inside temperature" returns `[WARNING] - [DatabaseManager]         Error fetching data for component TelemetryManager in table telemetry: Error binding parameter :type - probably unsupported type.`
This used to work fine 6 months ago, so picking its occured in recent-ish changes 

**To Reproduce**

Ask Alice for a telemetry value. IE: whats the kitchen temperature , whats the outside dewpoint etc 
Clicking a temperature icon in "my home" reports the temperature correctly, it's when asking her via voice

**Expected behavior**
Alice report back the telemetry value ... Eg: the inside temperature is 20C

**Logs**
Based on my initial tests there are a couple of errors i can see.

1. Line 197 of telemetryManager.py is `values['type'] = ttype` . When evaulated it returns <Telemetry.Temperature -'temperature> rather than just the enum value of"temperature" therefore the database fetch at around line 221 never finds the  correct value...... changing `values['type'] = 'temperature'` (as a temporary test) allows the database to fetch the required values and pass it to telemetry.py, **However**.....

2. in telemetry.py  this line `if data and 'value' in data.keys():` is in error for me according to pycharm. error is `Unresolved attribute reference 'keys' for class 'Iterable' ` ?

```
Paste your logs here
```

**Alice version**
1.0.0-rc1

**Additional context**
database example
![Kazam_screenshot_00037](https://user-images.githubusercontent.com/31381872/132984955-59408283-d714-43bb-8522-262f97f4c9fd.png)

**Comment by Psychokiller1888** [comment]
Just pushed a fix for it

**Comment by LazzaAU** [comment]
Thanks, that fixed the first part of it :), now i get 

`data line59 - Telemtry.py is [<sqlite3.Row object at 0x66c81220>]`

>[SkillManager]            Error dispatching message "GetTelemetryData" to Telemetry: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 269, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 561, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Telemetry/Telemetry.py", line 61, in telemetryIntent
    if data and 'value' in data.keys():
AttributeError: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 269, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 561, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Telemetry/Telemetry.py", line 61, in telemetryIntent
    if data and 'value' in data.keys():
AttributeError: 'list' object has no attribute 'keys'

**Comment by Psychokiller1888** [comment]
I'll have a revamp of that Sqlite.Row VS Dict mess, I think it's gonna be easier. The todo for that is there since I think 2 years :)

**Comment by Psychokiller1888** [comment]
Ok, just rewrote the whole thing, need to test before pushing though, can't do just now

**Comment by Psychokiller1888** [comment]
Should be fixed imo

**Comment by LazzaAU** [comment]
Getting closer :)

i had to add .value to the ttype on line 190 of telemetryManager for it to read the database. It now fetches and "data" variable is now a list with a dictionary inside so thats good, however i get this error when asking for temperature now.

>data line59 - Telemtry.py is [{'id': 237347, 'type': 'temperature', 'value': '25.1', 'service': 'HomeAssistant', 'deviceId': 52, 
'locationId': 5, 'timestamp': 1631792719}]

>[SkillManager]            Error dispatching message "GetTelemetryData" to Telemetry: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 264, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 561, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Telemetry/Telemetry.py", line 61, in telemetryIntent
    if data and 'value' in data.keys():
AttributeError: 'list' object has no attribute 'keys'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 264, in dispatchMessage
    consumed = skillInstance.onMessageDispatch(session)
  File "/home/pi/ProjectAlice/core/base/model/AliceSkill.py", line 561, in onMessageDispatch
    ret = function(session=session)
  File "/home/pi/ProjectAlice/skills/Telemetry/Telemetry.py", line 61, in telemetryIntent
    if data and 'value' in data.keys():
AttributeError: 'list' object has no attribute 'keys'

**Comment by LazzaAU** [comment]
I don't seem to have issues with asking for temperature etc now so the above seems good. However a roll on issue is now adding telemetry data to a graph in my home -> telemetry i get 

>[TelemetryApi] Failed getting telemetry data: 'str' object has no attribute 'value'
Traceback (most recent call last):
File "/home/pi/ProjectAlice/core/webApi/model/TelemetryApi.py", line 41, in get
rows = self.TelemetryManager.getData(ttype=ttype, deviceId=deviceId, locationId=locationId, historyTo=historyTo, historyFrom=historyFrom, everything=getAll)
File "/home/pi/ProjectAlice/core/util/TelemetryManager.py", line 190, in getData
values['type'] = ttype.value
AttributeError: 'str' object has no attribute 'value'
[08:52:00.664][unknown][TelemetryApi] Failed getting telemetry data: 'str' object has no attribute 'value'
Traceback (most recent call last):
File "/home/pi/ProjectAlice/core/webApi/model/TelemetryApi.py", line 41, in get
rows = self.TelemetryManager.getData(ttype=ttype, deviceId=deviceId, locationId=locationId, historyTo=historyTo, historyFrom=historyFrom, everything=getAll)
File "/home/pi/ProjectAlice/core/util/TelemetryManager.py", line 190, in getData
values['type'] = ttype.value
AttributeError: 'str' object has no attribute 'value'

**Comment by philipp2310** [comment]
fixed with #609 ?
or is there anythign still open here?

**Comment by LazzaAU** [comment]
Will test again shortly, cheers

**Comment by LazzaAU** [comment]
Appears to of been fixed now thank you :)
