### ISSUE TITLE
Can't start service after fresh install 

### ISSUE THREAD

**Issue by skkostas** [project-alice-assistant/ProjectAlice#588]
Hello,

I just installed the Alice by following  [Main unit manual setup](https://docs.projectalice.io/setup/manual-install.html)

after completed the main installation on one RPi4 B+ with 8G RAM, The Alice service didn't comes up so I followed the [Troubleshooting](https://docs.projectalice.io/setup/troubleshooting.html)!

I have the following error

```
[MqttManager]             Starting
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 119, in onStart
    mqttManager.onStart()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 94, in onStart
    self.connect()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 176, in connect
    self._mqttClient.connect(self.ConfigManager.getAliceConfigByName('mqttHost'), int(self.ConfigManager.getAliceConfigByName('mqttPort')))
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Error while starting managers: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 119, in onStart
    mqttManager.onStart()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 94, in onStart
    self.connect()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 176, in connect
    self._mqttClient.connect(self.ConfigManager.getAliceConfigByName('mqttHost'), int(self.ConfigManager.getAliceConfigByName('mqttPort')))
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[Project Alice]           Shutting down
Manager unknownManager was not running: 'MqttManager'
Error while sending onBooted to manager DeviceManager: 'NoneType' object has no attribute 'connected'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 174, in onBooted
    manager.onBooted()
  File "/home/pi/ProjectAlice/core/device/DeviceManager.py", line 126, in onBooted
    self.getMainDevice().connected = True
AttributeError: 'NoneType' object has no attribute 'connected'
[Project Alice]           Started in 1.87 seconds
[Project Alice]           Shutting down
Manager unknownManager was not running: 'MqttManager'
[Project Alice]           Shutdown completed, see you soon!
```

**This is all log**

```
[Initializer]     Starting Project Alice initialization
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
apt-transport-https is already the newest version (2.2.4).
automake is already the newest version (1:1.16.3-2).
dirmngr is already the newest version (2.2.27-2).
flac is already the newest version (1.3.3-2).
gcc is already the newest version (4:10.2.1-1+rpi1).
gfortran is already the newest version (4:10.2.1-1+rpi1).
git is already the newest version (1:2.30.2-1).
libatlas-base-dev is already the newest version (3.10.3-10+rpi1).
libffi-dev is already the newest version (3.3-6).
libicu-dev is already the newest version (67.1-7).
libpcre2-dev is already the newest version (10.36-2).
libtool is already the newest version (2.4.6-15).
libxml2-dev is already the newest version (2.9.10+dfsg-6.7).
libxslt1-dev is already the newest version (1.1.34-4).
make is already the newest version (4.3-4.1).
mosquitto is already the newest version (2.0.11-1).
mosquitto-clients is already the newest version (2.0.11-1).
mpg123 is already the newest version (1.26.4-1).
nginx is already the newest version (1.18.0-6.1).
pkg-config is already the newest version (0.29.2-1).
portaudio19-dev is already the newest version (19.6.0-1.1).
python3-pyaudio is already the newest version (0.2.11-1.3+b1).
python3-wheel is already the newest version (0.34.2-1).
unzip is already the newest version (6.0-26).
zip is already the newest version (3.0-12).
ffmpeg is already the newest version (7:4.3.3-0+rpt1+deb11u1).
libasound2-dev is already the newest version (1.2.4-1.1+rpt2).
python3-pip is already the newest version (20.3.4-4+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Hit:1 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
No local changes to save
Submodule path 'core/webui/public': checked out '8be485d679d74f41f1769dddccdddca60b9d954f'
Entering 'core/webui/public'
Previous HEAD position was 8be485d Merge pull request #9 from project-alice-assistant/1.0.0-rc1
Switched to branch 'builds_master'
Your branch is up to date with 'origin/builds_master'.
Entering 'core/webui/public'
hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libxslt1-dev' instead of 'libxslt-dev'
apt-transport-https is already the newest version (2.2.4).
automake is already the newest version (1:1.16.3-2).
dirmngr is already the newest version (2.2.27-2).
flac is already the newest version (1.3.3-2).
gcc is already the newest version (4:10.2.1-1+rpi1).
gfortran is already the newest version (4:10.2.1-1+rpi1).
git is already the newest version (1:2.30.2-1).
libatlas-base-dev is already the newest version (3.10.3-10+rpi1).
libffi-dev is already the newest version (3.3-6).
libicu-dev is already the newest version (67.1-7).
libpcre2-dev is already the newest version (10.36-2).
libtool is already the newest version (2.4.6-15).
libxml2-dev is already the newest version (2.9.10+dfsg-6.7).
libxslt1-dev is already the newest version (1.1.34-4).
make is already the newest version (4.3-4.1).
mosquitto is already the newest version (2.0.11-1).
mosquitto-clients is already the newest version (2.0.11-1).
mpg123 is already the newest version (1.26.4-1).
nginx is already the newest version (1.18.0-6.1).
pkg-config is already the newest version (0.29.2-1).
portaudio19-dev is already the newest version (19.6.0-1.1).
python3-pyaudio is already the newest version (0.2.11-1.3+b1).
python3-wheel is already the newest version (0.34.2-1).
unzip is already the newest version (6.0-26).
zip is already the newest version (3.0-12).
ffmpeg is already the newest version (7:4.3.3-0+rpt1+deb11u1).
libasound2-dev is already the newest version (1.2.4-1.1+rpt2).
python3-pip is already the newest version (20.3.4-4+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Missing key **False** in provided yaml file.
[Initializer]     Config file already existing and user not wanting to rewrite, aborting
[Project Alice]           Starting Alice main unit
[CommonsManager]          Initializing
[StateManager]            Initializing
[SubprocessManager]       Initializing
[ConfigManager]           Initializing
[ConfigManager]           Checking Alice configuration file
[DatabaseManager]         Initializing
[SkillManager]            Initializing
[WidgetManager]           Initializing
[DeviceManager]           Initializing
[AudioManager]            Initializing
[LanguageManager]         Initializing
[LanguageManager]         Active language set to en-US
[LanguageManager]         Default language set to en-US
[ASRManager]              Initializing
[TTSManager]              Initializing
[ThreadManager]           Initializing
[MqttManager]             Initializing
[TimeManager]             Initializing
[UserManager]             Initializing
[MultiIntentManager]      Initializing
[TelemetryManager]        Initializing
[LocationManager]         Initializing
[InternetManager]         Initializing
[WakewordRecorder]        Initializing
[TalkManager]             Initializing
[WebUIManager]            Initializing
[ApiManager]              Initializing
[NodeRedManager]          Initializing
[SkillStoreManager]       Initializing
[DialogTemplateManager]   Initializing
[AssistantManager]        Initializing
[NluManager]              Initializing
[AliceWatchManager]       Initializing
[DialogManager]           Initializing
[WakewordManager]         Initializing
[WebUINotificationManager] Initializing
[CommonsManager]          Starting
[StateManager]            Starting
[ConfigManager]           Starting
[LanguageManager]         Starting
[WebUINotificationManager] Starting
[LocationManager]         Starting
[LocationManager]         Loaded location The Hive
[LocationManager]         Loaded 1 location
[AudioManager]            Starting
[AudioManager]            Using default for audio input
[AudioManager]            Using default for audio output
[InternetManager]         Starting
[DatabaseManager]         Starting
[UserManager]             Starting
[UserManager]             Loaded 0 user
[MqttManager]             Starting
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 119, in onStart
    mqttManager.onStart()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 94, in onStart
    self.connect()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 176, in connect
    self._mqttClient.connect(self.ConfigManager.getAliceConfigByName('mqttHost'), int(self.ConfigManager.getAliceConfigByName('mqttPort')))
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Error while starting managers: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 119, in onStart
    mqttManager.onStart()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 94, in onStart
    self.connect()
  File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 176, in connect
    self._mqttClient.connect(self.ConfigManager.getAliceConfigByName('mqttHost'), int(self.ConfigManager.getAliceConfigByName('mqttPort')))
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/home/pi/ProjectAlice/venv/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
[Project Alice]           Shutting down
Manager unknownManager was not running: 'MqttManager'
Error while sending onBooted to manager DeviceManager: 'NoneType' object has no attribute 'connected'
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 174, in onBooted
    manager.onBooted()
  File "/home/pi/ProjectAlice/core/device/DeviceManager.py", line 126, in onBooted
    self.getMainDevice().connected = True
AttributeError: 'NoneType' object has no attribute 'connected'
[Project Alice]           Started in 1.87 seconds
[Project Alice]           Shutting down
Manager unknownManager was not running: 'MqttManager'
[Project Alice]           Shutdown completed, see you soon!
```

Does anyone have any idea where the problem is?

**Comment by Psychokiller1888** [comment]
Maybe Mosquito service not running?

**Comment by skkostas** [comment]
Hello @Psychokiller1888 and thank you for your reply

in /boot/ProjectAlice.yaml

i have added

```
# Connection
mqttHost: Home Assistant IP
mqttPort: 1883
mqttUser: MQTT User
mqttPassword: MQTT Password
mqttTLSFile:
```

The Project Alice need local MQTT?

**Comment by Psychokiller1888** [comment]
Are you running on rc1? You can use a distant mqtt server, although I haven't tested it myself. On discord, we have some people using it in case

**Comment by skkostas** [comment]
@Psychokiller1888 how can i see the version?

also the MQTT running correctly  on Rpi with Alice i changed the # Connection with the local server! and i have same issue!

![explorer_7yewQEN0RM](https://user-images.githubusercontent.com/5460613/142766434-64ee088a-bc92-4334-8887-26c34f54cb65.png)

**Comment by skkostas** [comment]
i Added the `allow_anonymous true` in the /etc/mosquitto/mosquitto.conf and worked

**Comment by Psychokiller1888** [comment]
way to go, good find, noted, thanks!
