### ISSUE TITLE
Update connection error

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#621]
I got this below error today. If you recall i suffer from crap internet in most places i move to and therefore my internet always comes and goes. 

should i be getting connectionError's if using a offline voice ??

>[DeviceManager]                     Device WebInterface has not given a signal since 5 seconds or more
[ASRManager]                        Internet lost, switching to offline Asr
[GoogleAsr]                         Stopping Google Asr
[GoogleAsr]                         Checking dependencies
[ASRManager]                        Asr did not satisfy the user settings, falling back to coqui
[CoquiAsr]                          Checking dependencies
[CoquiAsr]                          Starting Coqui Asr
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x666f1050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/project-alice-assistant/ProjectAlice/branches (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x666f1050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/home/pi/ProjectAlice/core/util/ThreadManager.py", line 113, in onTimerEnd
    timer.callback(*timer.args, **timer.kwargs)
  File "/home/pi/ProjectAlice/core/util/TimeManager.py", line 41, in timerSignal
    self.broadcast(signal, exceptions=[self.name], propagateToSkills=True)
  File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 142, in broadcast
    self.SkillManager.skillBroadcast(method=method, **kwargs)
  File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 1154, in skillBroadcast
    func(**kwargs)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 264, in settingDecorator
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/skills/AliceCore/AliceCore.py", line 867, in onFullHour
    self.ProjectAlice.updateProjectAlice()
  File "/home/pi/ProjectAlice/core/ProjectAlice.py", line 175, in updateProjectAlice
    req = requests.get(url=f'{constants.GITHUB_API_URL}/ProjectAlice/branches', auth=SuperManager.getInstance().ConfigManager.githubAuth)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/project-alice-assistant/ProjectAlice/branches (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x666f1050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

[ThreadManager]                     Cleaned 1 dead timer
[ThreadManager]                     Cleaned 4 dead thread
[CoquiAsr]                          Loading Model
TensorFlow: v2.3.0-6-g23ad988fcde
 Coqui STT: v0.10.0-alpha.4-78-g1f3d2dab
[CoquiAsr]                          Model Loaded
[CoquiAsr]                          Scorer Loaded
[CoquiAsr]                          Starting Coqui Asr

**Comment by philipp2310** [comment]
The cause is alice tries to update, nothing to do with coqui:
File "/home/pi/ProjectAlice/skills/AliceCore/AliceCore.py", line 867, in onFullHour
self.ProjectAlice.updateProjectAlice()

better error handling when the request fails would be nice :)

**Comment by philipp2310** [comment]
caught exception and writing to log -> no more stack trace
