### ISSUE TITLE
bug reporting - nothing to report ?

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#623]
Just for reference in case it gets mentioned by others ?

Just got this below log. Bug reporting was enabled and i had a handfull of errors (last traceback was me ctl+c during training,, oops ) but anyway, it said "nothing to report". Should it though ? due to the first traceback  or could that be because my internet may of dropped offline at the time ?

>[Initializer]                       Starting Project Alice initialization
[PreInitializer]                    No initialization needed
[Project Alice]                     Starting Alice main unit (version 1.0.0-rc3)
[BugReportManager]                  Initializing
[BugReportManager]                  Flag file detected, recording errors for this run
[BugReportManager]                  Project Alice logs
[BugReportManager]                  Git commit id: 3da81411b327ea3e9537b1e9c3a9017539bfda24
[CommonsManager]                    Initializing
[StateManager]                      Initializing
[SubprocessManager]                 Initializing
[ConfigManager]                     Initializing
[ConfigManager]                     Checking Alice configuration file
[DatabaseManager]                   Initializing
[SkillManager]                      Initializing
[WidgetManager]                     Initializing
[DeviceManager]                     Initializing
[AudioManager]                      Initializing
[LanguageManager]                   Initializing
[LanguageManager]                   Active language set to en-US
[LanguageManager]                   Default language set to en-US
[ASRManager]                        Initializing
[TTSManager]                        Initializing
[ThreadManager]                     Initializing
[MqttManager]                       Initializing
[TimeManager]                       Initializing
[UserManager]                       Initializing
[MultiIntentManager]                Initializing
[TelemetryManager]                  Initializing
[LocationManager]                   Initializing
[InternetManager]                   Initializing
[WakewordRecorder]                  Initializing
[TalkManager]                       Initializing
[WebUIManager]                      Initializing
[ApiManager]                        Initializing
[NodeRedManager]                    Initializing
[SkillStoreManager]                 Initializing
[DialogTemplateManager]             Initializing
[AssistantManager]                  Initializing
[NluManager]                        Initializing
[AliceWatchManager]                 Initializing
[DialogManager]                     Initializing
[WakewordManager]                   Initializing
[WebUINotificationManager]          Initializing
[BugReportManager]                  Starting
[CommonsManager]                    Starting
[StateManager]                      Starting
[ThreadManager]                     Started new thread subprocessManager, thread count: 1
[ConfigManager]                     Starting
[LanguageManager]                   Starting
[WebUINotificationManager]          Starting
[LocationManager]                   Starting
[LocationManager]                   Loaded location Home
[LocationManager]                   Loaded location Outside
[LocationManager]                   Loaded location Bedroom
[LocationManager]                   Loaded location Bathroom
[LocationManager]                   Loaded location Inside
[LocationManager]                   Loaded location Entrance
[LocationManager]                   Loaded location Lounge
[LocationManager]                   Loaded location Kitchen
[LocationManager]                   Loaded location StoreRoom
[LocationManager]                   Loaded location Ute
[LocationManager]                   Loaded 10 locations
[AudioManager]                      Starting
[AudioManager]                      Using seeed-4mic-voicecard: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 (hw:1,0) for audio input
[AudioManager]                      Using bcm2835 Headphones: - (hw:0,0) for audio output
[InternetManager]                   Starting
[ThreadManager]                     Started new thread internetCheckThread, thread count: 3
[DatabaseManager]                   Starting
[UserManager]                       Starting
[UserManager]                       Loaded 2 users
[MqttManager]                       Starting
[AliceWatchManager]                 Starting
[ApiManager]                        Starting
 * Serving Flask app 'core.webApi.ApiManager' (lazy loading)
[ThreadManager]                     Started new thread API, thread count: 5
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
[ASRManager]                        Starting
   Use a production WSGI server instead.
 * Debug mode: on
[GoogleAsr]                         Checking dependencies
[GoogleAsr]                         Starting Google Asr
[DialogManager]                     Starting
[MultiIntentManager]                Starting
[SkillStoreManager]                 Starting
[TelemetryManager]                  Starting
[ThreadManager]                     Starting
[TimeManager]                       Starting
[TTSManager]                        Starting
[AmazonTts]                         Checking dependencies
[AmazonTts]                         Language from config: en-GB
[AmazonTts]                         Type from config: male
[AmazonTts]                         Voice from config: Brian
[WakewordManager]                   Starting
[SnipsWakeword]                     Checking dependencies
[SnipsWakeword]                     Starting Snips hotword
[SubprocessManager]                 Starting the subprocess SnipsHotword
[WebUIManager]                      Starting
[WebUIManager]                      Started nginx server
[ThreadManager]                     Started new thread DisplayResourceUsage, thread count: 6
[TalkManager]                       Starting
[NluManager]                        Starting
[SkillManager]                      Starting
[SkillManager]                      Checking for skill updates
[SkillManager]                      AliceCore - Version 1.5.28 in rc
[SkillManager]                      Skill AliceDevTools is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      AliceVolume - Version 1.0.15 in rc - Locked for local changes!
[SkillManager]                      BackUpAlice - Version 1.1.10 in rc
[SkillManager]                      ContextSensitive - Version 1.0.33 in rc
[SkillManager]                      DateDayTimeYear - Version 1.1.3 in rc
[SkillManager]                      HLCpattern - Version 1.1.4 in rc
[SkillManager]                      HomeAssistant - Version 3.1.8 in rc - Locked for local changes!
[SkillManager]                      RedQueen - Version 1.0.40 in rc - Locked for local changes!
[SkillManager]                      Reminder - Version 1.2.4 in rc
[SkillManager]                      Telegram - Version 1.5.4 in rc
[SkillManager]                      Telemetry - Version 1.3.5 in rc
[SkillManager]                      Skill WaterTankLevel is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      Found 0 skill update
[ConfigManager]                     Checking configuration for skill AliceCore
[ConfigManager]                     Checking configuration for skill AliceDevTools
[ConfigManager]                     Checking configuration for skill AliceVolume
[ConfigManager]                     Checking configuration for skill BackUpAlice
[ConfigManager]                     Checking configuration for skill ContextSensitive
[ConfigManager]                     Checking configuration for skill DateDayTimeYear
[ConfigManager]                     Checking configuration for skill HLCpattern
[ConfigManager]                     Checking configuration for skill HomeAssistant
[ConfigManager]                     Checking configuration for skill RedQueen
[ConfigManager]                     Checking configuration for skill Reminder
[ConfigManager]                     Checking configuration for skill Telegram
[ConfigManager]                     Checking configuration for skill Telemetry
[ConfigManager]                     Checking configuration for skill WaterTankLevel
[AliceCore]                         Starting
[AliceCore]                         Found 2 device type
[AliceCore]                         Started!
[AliceDevTools]                     Starting
[AliceDevTools]                     Started!
[AliceVolume]                       Starting
[AliceVolume]                       Started!
[BackUpAlice]                       Starting
[BackUpAlice]                       Started!
[ContextSensitive]                  Starting
[ContextSensitive]                  Started!
[DateDayTimeYear]                   Starting
[DateDayTimeYear]                   Found 2 widgets
[DateDayTimeYear]                   No widget config template for widget type Clock found
[DateDayTimeYear]                   No widget config template for widget type Date found
[DateDayTimeYear]                   Started!
[HLCpattern]                        Starting
[HLCpattern]                        Started!
[HomeAssistant]                     Starting
[HomeAssistant]                     Found 10 device type
[HomeAssistant]                     Started!
[RedQueen]                          Starting
[RedQueen]                          Started!
[RedQueen]                          Found existing Red Queen identity
[Reminder]                          Starting
[Reminder]                          Started!
[Reminder]                          Doing database maintenance
[Reminder]                          Checking for active timers in MyReminders database
[Reminder]                          Checking for active timers in MyTimer database
[Reminder]                          Checking for active timers in MyAlarm database
[Telegram]                          Starting
[Telegram]                          Started!
[Telegram]                          Loaded 1 user
[Telemetry]                         Starting
[Telemetry]                         Started!
[WaterTankLevel]                    Starting
[WaterTankLevel]                    Started!
[SkillManager]                      Skills started. 60 intents supported
[DeviceManager]                     Starting
[DeviceManager]                     Loaded 59 device instance
[WidgetManager]                     Starting
[WidgetManager]                     Loaded 2 pages
[WidgetManager]                     Loaded 2 templates from 1 skill
[WidgetManager]                     Loaded 1 active widget
[DialogTemplateManager]             Starting
[AssistantManager]                  Starting
[AssistantManager]                  Checking assistant
[AssistantManager]                  Assistant seems consistent
[DialogTemplateManager]             Checking data for skill AliceCore
[DialogTemplateManager]             Skill AliceCore has changes in language en
[DialogTemplateManager]             Checking data for skill AliceDevTools
[DialogTemplateManager]             Checking data for skill AliceVolume
[DialogTemplateManager]             Checking data for skill BackUpAlice
[DialogTemplateManager]             Checking data for skill ContextSensitive
[DialogTemplateManager]             Checking data for skill DateDayTimeYear
[DialogTemplateManager]             Checking data for skill HLCpattern
[DialogTemplateManager]             Checking data for skill HomeAssistant
[DialogTemplateManager]             Skill HomeAssistant has changes in language en
[DialogTemplateManager]             Checking data for skill RedQueen
[DialogTemplateManager]             Checking data for skill Reminder
[DialogTemplateManager]             Checking data for skill Telegram
[DialogTemplateManager]             Checking data for skill Telemetry
[DialogTemplateManager]             Checking data for skill WaterTankLevel
[DialogTemplateManager]             Building dialog templates cache
[SnipsNlu]                          Preparing NLU training file
[SnipsNlu]                          Training Snips NLU
[SnipsNlu]                          Generated dataset for training
[SnipsNlu]                          Begin training...
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/webApi/model/SkillsApi.py", line 383, in getGitStatus
    for (name, rem) in git.remote.items():
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 71, in remote
    return dict((rem.user, rem) for rem in [Remote(statusString=st) for st in remotes.split('\n')])
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 71, in <listcomp>
    return dict((rem.user, rem) for rem in [Remote(statusString=st) for st in remotes.split('\n')])
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 336, in __init__
    self.name, dummy, self.url, direction = statusString.split(' ')
ValueError: not enough values to unpack (expected 4, got 1)
[SkillManager]                      Checking for skill updates
[SkillManager]                      AliceVolume - Version 1.0.14 < 1.0.15 in rc
[SkillManager]                      Found 1 skill update
[SkillManager]                      Now updating skill AliceVolume
[AliceVolume]                       Stopped
[ConfigManager]                     Checking configuration for skill AliceVolume
[AliceVolume]                       Starting
[AliceVolume]                       Started!
[SkillManager]                      Updated skill AliceVolume to version 1.0.15
Traceback (most recent call last):
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/util/Decorators.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/ProjectAlice/core/webApi/model/SkillsApi.py", line 383, in getGitStatus
    for (name, rem) in git.remote.items():
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 71, in remote
    return dict((rem.user, rem) for rem in [Remote(statusString=st) for st in remotes.split('\n')])
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 71, in <listcomp>
    return dict((rem.user, rem) for rem in [Remote(statusString=st) for st in remotes.split('\n')])
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/AliceGit/Git.py", line 336, in __init__
    self.name, dummy, self.url, direction = statusString.split(' ')
ValueError: not enough values to unpack (expected 4, got 1)
^C[SubprocessManager]                 Subprocess SnipsHotword went defunct
[SubprocessManager]                 Restarting Subprocess SnipsHotword
[SnipsNlu] Error while training Snips NLU: Traceback (most recent call last):
  File "./venv/bin/snips-nlu", line 10, in <module>
    sys.exit(main())
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/init.py", line 52, in main
    args.func(args)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/training.py", line 26, in _train
    args_namespace.random_seed)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/cli/training.py", line 56, in train
    engine = SnipsNLUEngine(config, random_state=random_state).fit(dataset)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/common/log_utils.py", line 30, in wrapped
    res = fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/nlu_engine/nlu_engine.py", line 126, in fit
    recycled_parser.fit(dataset, force_retrain)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/common/log_utils.py", line 30, in wrapped
    res = fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/intent_parser/probabilistic_intent_parser.py", line 94, in fit
    self.slot_fillers[intent_name].fit(dataset, intent_name)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/common/log_utils.py", line 30, in wrapped
    res = fn(*args, **kwargs)
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/slot_filler/crf_slot_filler.py", line 148, in fit
    for sample in crf_samples]
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/slot_filler/crf_slot_filler.py", line 148, in <listcomp>
    for sample in crf_samples]
  File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/snips_nlu/slot_filler/crf_slot_filler.py", line 207, in compute_features
    if drop_out and self.random_state.rand() < f_drop_out:
KeyboardInterrupt

[Traceback]                         NoneType: None
[SnipsNlu]                          Snips NLU training failed
[Traceback]                         NoneType: None
[NodeRedManager]                    Starting
[AudioManager]                      Starting audio publisher
[ThreadManager]                     Started new thread audioPublisher, thread count: 11
[ThreadManager]                     Started new thread checkHeartbeats, thread count: 13
[ThreadManager]                     Started new thread heartBeatThread-1641461545, thread count: 13
[HomeAssistant]                     HomeAssistant Connected
[HomeAssistant]                     Sending Heartbeat connection requests
[DeviceManager]                     Device named heater state (c5184bcf-65c2-4390-902b-5bb525ebe2b4) in Bedroom connected
[DeviceManager]                     Device named alarm (0ee62473-660d-49c4-ba73-5d5f8e591fce) in Lounge connected
[DeviceManager]                     Device named people home (7bd42d49-ec11-4735-aa56-ff0030712715) in Lounge connected
[DeviceManager]                     Device named awning switch - on is open (0655f95e-f775-48c8-a176-35fe56d99b83) in Outside connected
[DeviceManager]                     Device named rain water hose connected (87af7090-1885-4107-99bb-3699aa7f5ea5) in Kitchen connected
[DeviceManager]                     Device named rain water low level (108bd0cb-b45a-4731-a9eb-2baf845463bf) in Outside connected
[DeviceManager]                     Device named rain water mid level (cf91f500-9a4b-45a5-98e7-276ddb57e760) in Outside connected
[DeviceManager]                     Device named rain water high level (3f59590a-cb93-4104-a4d0-94d7aaf77efb) in Outside connected
[DeviceManager]                     Device named rain water pump running (326a3433-8ab4-4a03-b55f-161118231964) in Kitchen connected
[DeviceManager]                     Device named kitchen lights (2d65223c-79eb-48a9-910b-d5dd89e25adb) in Inside connected
[DeviceManager]                     Device named bedroom lights (8f6bff74-3db1-4638-8cda-74f039ed27d7) in Bedroom connected
[DeviceManager]                     Device named bathroom lights (bb7a59cc-f9fb-4ee3-888d-168936908657) in Bathroom connected
[DeviceManager]                     Device named lounge lights (b89b2e4a-d397-4eaa-865e-1006218967ac) in Lounge connected
[DeviceManager]                     Device named outside lights (848a1211-9e0a-453f-bbaf-0264f19149d5) in Outside connected
[DeviceManager]                     Device named all main lights (70fc6fe5-98c3-4dae-8a74-93f189f41f34) in Home connected
[DeviceManager]                     Device named laptop charger (ae8e6f5a-68ef-4bc6-ad44-1def58a2a9aa) in Lounge connected
[DeviceManager]                     Device named ute power (e072e1a7-68e3-4379-a003-4afbe74f8dea) in Ute connected
[DeviceManager]                     Device named pillow light (950190b5-a8f8-488b-be85-7e26e44d6cbd) in Bedroom connected
[DeviceManager]                     Device named external light (d9622b15-a1c4-41c8-93b5-28abab151b85) in Outside connected
[DeviceManager]                     Device named pillow light (0ef4ff43-fb07-4982-9d73-a77cb97996a8) in Bedroom connected
[DeviceManager]                     Device named awning light (34709c08-4239-47eb-85d7-4780bc7ec3b1) in Outside connected
[DeviceManager]                     Device named couch light (f62983f5-e18d-4e65-a29e-1a766a658b89) in Lounge connected
[DeviceManager]                     Device named window light (9ed3c3b2-2647-4c1b-a25a-ca8dcf3dd090) in Bedroom connected
[DeviceManager]                     Device named witi (47afe2b6-97a4-4586-86a8-8c281e8cb0a7) in Lounge connected
[DeviceManager]                     Device named sink light (42141829-be1f-4f67-8a58-d005f5c66a4e) in Kitchen connected
[DeviceManager]                     Device named awning light (005284fd-1834-4f0b-8dd0-99698b06fa27) in Outside connected
[DeviceManager]                     Device named window light (c92f4189-376a-4172-9f3c-ba8a6fa5921b) in Bedroom connected
[DeviceManager]                     Device named couch light (d05fa1dd-3a1e-4641-8ceb-b306f1f7d6f7) in Lounge connected
[DeviceManager]                     Device named round lights (6b58eb1c-8100-4a4d-a948-ba9b462cf4c3) in Kitchen connected
[DeviceManager]                     Device named toilet light (03370462-de54-4327-96d9-9662e1eb8372) in Bathroom connected
[DeviceManager]                     Device named mirror light (4a419d94-b223-4ca9-8421-afc60284af69) in Bathroom connected
[DeviceManager]                     Device named external light (5c9f7cc0-c07d-4f3b-b811-bb1ae10d6180) in Outside connected
[DeviceManager]                     Device named fridge fan (9bc27783-75fa-4590-8b70-65f9eba9f459) in Kitchen connected
[DeviceManager]                     Device named 240 power (3e8ddadd-df80-4036-a9d8-9085016c78a7) in Entrance connected
[DeviceManager]                     Device named diesel heater on (ecb257c6-79e0-47f0-884f-707c5c9b101d) in Bedroom connected
[DeviceManager]                     Device named diesel heater off (24199336-122f-4243-a101-8503eae2e9de) in Bedroom connected
[DeviceManager]                     Device named main light (de3eea51-d152-4a17-8bfc-b27f9b192172) in Bedroom connected
[DeviceManager]                     Device named entrance light (7a373414-542a-4d54-b186-0de397055b63) in Entrance connected
[DeviceManager]                     Device named rain water pump (9f26279c-e49e-4b76-9977-5af2c568d427) in Kitchen connected
[DeviceManager]                     Device named toilet motion (423aa33e-e58e-49ae-ab64-aad3d50e57ca) in Bathroom connected
[DeviceManager]                     Device named ute rear battery voltage (1356f9bc-8200-4d91-8f5b-83227684d687) in Ute connected
[DeviceManager]                     Device named ute rear battery current (6f8743c3-ff4e-4159-9975-3923878155ae) in Ute connected
[DeviceManager]                     Device named ute rear battery power (4d55db16-9f28-4c15-8923-ebd8aecb7fdd) in Ute connected
[DeviceManager]                     Device named outside temperature (afbcbe80-f42c-47f1-85e1-bc96e4b6d924) in Outside connected
[DeviceManager]                     Device named outside humidity (1b9f2cb9-49ef-4274-8b53-26ce391d0f0f) in Outside connected
[DeviceManager]                     Device named outside pressure (9a6936fe-7843-40ba-b651-a71767fcb069) in Outside connected
[DeviceManager]                     Device named inside temperature (879104e0-aabb-4d78-b0ef-2b97654fc44f) in Inside connected
[DeviceManager]                     Device named inside humidity (bdd4e9a3-01f6-4f6d-bfae-24eeaea73261) in Inside connected
[DeviceManager]                     Device named inside dewpoint (3509172c-e560-4cbe-8984-622a1b8ef1b9) in Inside connected
[DeviceManager]                     Device named inside pressure (813f3961-e167-4ad9-a57a-992b4895cc51) in Inside connected
[DeviceManager]                     Device named inside gas (8553c120-4dd0-41eb-b84a-588f64bdb3a7) in Inside connected
[DeviceManager]                     Device named rainwatervalve (dc0e0f1c-0b0a-4ede-a9bb-d7c78be07e3a) in StoreRoom connected
[DeviceManager]                     Device named rain water tank (f6e97126-cb36-4ec7-94f6-64a583216ef6) in StoreRoom connected
[DeviceManager]                     Device named fresh water tank 1 (110229ea-835f-4fef-a580-4b4bdde18b23) in StoreRoom connected
[DeviceManager]                     Device named fresh water tank 2 (0d30b82d-2bba-4add-bb2e-b66704f95113) in StoreRoom connected
[DeviceManager]                     Device named grey water tank 1 (6bd3d0e4-d949-48ff-b2d5-75be3c6c67fe) in StoreRoom connected
[DeviceManager]                     Device named outside temperature bme280 dewpoint (17b8b899-9682-4b5e-a975-e191b0288a5e) in StoreRoom connected
[SnipsNlu]                          Starting Snips NLU
[SubprocessManager]                 Starting the subprocess SnipsNLU
[Project Alice]                     Started in 135.97 seconds
[Project Alice]                     Shutting down
[SkillManager]                      Stopping
[AliceCore]                         Stopped
[AliceDevTools]                     Stopped
[BackUpAlice]                       Stopped
[ContextSensitive]                  Stopped
[DateDayTimeYear]                   Stopped
[HLCpattern]                        Stopped
[AudioManager]                      Playing wav stream using bcm2835 Headphones: - (hw:0,0) audio output from device Alice (channels: 1, rate: 16000)
[HomeAssistant]                     Backing up dialog file
[HomeAssistant]                     Stopped
[RedQueen]                          Stopped
[Reminder]                          Stopped
[Telegram]                          Stopped
[Telemetry]                         Stopped
[WaterTankLevel]                    Stopped
[AliceVolume]                       Stopped
[AliceWatchManager]                 Stopping
[ApiManager]                        Stopping
[GoogleAsr]                         Stopping Google Asr
[DialogManager]                     Stopping
[MultiIntentManager]                Stopping
[SkillStoreManager]                 Stopping
[TelemetryManager]                  Stopping
[ThreadManager]                     Stopping
[AudioManager]                      Playing bytes finished
[TimeManager]                       Stopping
[TTSManager]                        Stopping
[WakewordManager]                   Stopping
[SnipsWakeword]                     Stopping Snips hotword
[WebUIManager]                      Stopping
[WebUIManager]                      Stopped nginx server
[ConfigManager]                     Stopping
[AudioManager]                      Stopping
[LanguageManager]                   Stopping
[LocationManager]                   Stopping
[DeviceManager]                     Stopping
[ThreadManager]                     Terminated thread heartBeatThread-1641461545, thread count: 10
[TalkManager]                       Stopping
[DatabaseManager]                   Stopping
[UserManager]                       Stopping
[WebUINotificationManager]          Stopping
[WidgetManager]                     Stopping
[DialogTemplateManager]             Stopping
[AssistantManager]                  Stopping
[NluManager]                        Stopping
[SnipsNlu]                          Stopping Snips NLU
[InternetManager]                   Stopping
[NodeRedManager]                    Stopping
[StateManager]                      Stopping
[SubprocessManager]                 Stopping
[MqttManager]                       Stopping
[BugReportManager]                  Stopping
[BugReportManager]                  Nothing to report
[Project Alice]                     Shutdown completed, see you soon!

**Comment by Psychokiller1888** [comment]
I would say that's because CTRL-C stopped her
