### ISSUE TITLE
Reset cycle

### ISSUE THREAD

**Issue by cyberlyra** [project-alice-assistant/ProjectAlice#630]
Alice keeps restarting itself repeatedly. I include the full startup to shutdown cycle:

```
Jan 15 17:09:37 ProjectAlice systemd[1]: ProjectAlice.service: Service RestartSec=5s expired, scheduling restart.
Jan 15 17:09:37 ProjectAlice systemd[1]: ProjectAlice.service: Scheduled restart job, restart counter is at 10.
Jan 15 17:09:37 ProjectAlice systemd[1]: Stopped Project Alice.
Jan 15 17:09:37 ProjectAlice systemd[1]: Starting Project Alice...
Jan 15 17:09:42 ProjectAlice systemd[1]: Started Project Alice.
Jan 15 17:09:43 ProjectAlice python[2495]: TERM environment variable not set.
Jan 15 17:09:43 ProjectAlice python[2495]: #033[39m[Initializer]                       Starting Project Alice initialization#033[0m
Jan 15 17:09:43 ProjectAlice python[2495]: #033[39m[PreInitializer]                    No initialization needed#033[0m
Jan 15 17:09:43 ProjectAlice python[2495]: #033[39m[Project Alice]                     Starting Alice main unit (version 1.0.0-rc3)#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[BugReportManager]                  #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[CommonsManager]                    #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[StateManager]                      #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[SubprocessManager]                 #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ConfigManager]                     #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ConfigManager]                     Checking Alice configuration file#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[DatabaseManager]                   #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WidgetManager]                     #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[DeviceManager]                     #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AudioManager]                      #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LanguageManager]                   #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LanguageManager]                   Active language set to #033[1men-US#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LanguageManager]                   Default language set to #033[1men-US#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ASRManager]                        #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[TTSManager]                        #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ThreadManager]                     #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[MqttManager]                       #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[TimeManager]                       #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[UserManager]                       #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[MultiIntentManager]                #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[TelemetryManager]                  #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LocationManager]                   #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[InternetManager]                   #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WakewordRecorder]                  #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[TalkManager]                       #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WebUIManager]                      #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ApiManager]                        #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[NodeRedManager]                    #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[SkillStoreManager]                 #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[DialogTemplateManager]             #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AssistantManager]                  #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[NluManager]                        #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AliceWatchManager]                 #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[DialogManager]                     #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WakewordManager]                   #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WebUINotificationManager]          #033[2mInitializing#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[BugReportManager]                  Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[CommonsManager]                    Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[StateManager]                      Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[ConfigManager]                     Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LanguageManager]                   Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[WebUINotificationManager]          Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LocationManager]                   Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LocationManager]                   Loaded location #033[1mThe Hive#033[0;39m#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[LocationManager]                   Loaded #033[1m1#033[0;39m location#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AudioManager]                      Starting#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AudioManager]                      Using #033[1mUSB Camera-B4.09.24.1: Audio (hw:1,0)#033[0;39m for audio input#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[AudioManager]                      Using #033[1mbcm2835 Headphones: - (hw:0,0)#033[0;39m for audio output#033[0m
Jan 15 17:09:46 ProjectAlice python[2495]: #033[39m[InternetManager]                   Starting#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[DatabaseManager]                   Starting#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[UserManager]                       Starting#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[UserManager]                       Loaded #033[1m1#033[0;39m user#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[MqttManager]                       Starting#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[AliceWatchManager]                 Starting#033[0m
Jan 15 17:09:47 ProjectAlice python[2495]: #033[39m[ApiManager]                        Starting#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]:  * Serving Flask app 'core.webApi.ApiManager' (lazy loading)
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[ASRManager]                        Starting#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]:  * Environment: production
Jan 15 17:09:54 ProjectAlice python[2495]:    WARNING: This is a development server. Do not use it in a production deployment.
Jan 15 17:09:54 ProjectAlice python[2495]:    Use a production WSGI server instead.
Jan 15 17:09:54 ProjectAlice python[2495]:  * Debug mode: off
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[SnipsAsr]                          Checking dependencies#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[SnipsAsr]                          Starting Snips Asr#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[SubprocessManager]                 Starting the subprocess SnipsASR#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[DialogManager]                     Starting#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[MultiIntentManager]                Starting#033[0m
Jan 15 17:09:54 ProjectAlice python[2495]: #033[39m[SkillStoreManager]                 Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[TelemetryManager]                  Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[ThreadManager]                     Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[TimeManager]                       Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[TTSManager]                        Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[PicoTts]                           Checking dependencies#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[PicoTts]                           Language from config: #033[1men-US#033[0;39m#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[PicoTts]                           Type from config: #033[1mmale#033[0;39m#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[PicoTts]                           Voice from config: #033[1men-US#033[0;39m#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[WakewordManager]                   Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[SnipsWakeword]                     Checking dependencies#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[SnipsWakeword]                     Starting #033[1mSnips hotword#033[0;39m#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[SubprocessManager]                 Starting the subprocess SnipsHotword#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[WebUIManager]                      Starting#033[0m
Jan 15 17:09:55 ProjectAlice systemd[1]: Starting A high performance web server and a reverse proxy server...
Jan 15 17:09:55 ProjectAlice systemd[1]: Started A high performance web server and a reverse proxy server.
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[WebUIManager]                      Started nginx server#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[TalkManager]                       Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[NluManager]                        Starting#033[0m
Jan 15 17:09:55 ProjectAlice python[2495]: #033[39m[SkillManager]                      Starting#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      Checking for skill updates#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mAliceCore#033[0;39m - Version 1.5.29 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mCalculator#033[0;39m - Version 1.0.32 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mContextSensitive#033[0;39m - Version 1.0.33 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[SkillManager]                      Error checking updates for skill #033[1mDateDayTimeYear#033[0;31m: Expecting value: line 1 column 1 (char 0)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                         Traceback (most recent call last):#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 1073, in checkForSkillUpdates#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             installer = json.loads(self.getSkillInstallFilePath(skillName=skillName).read_text())#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/#033[4minit#033[0;31m.py", line 348, in loads#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             return _default_decoder.decode(s)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/decoder.py", line 337, in decode#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             obj, end = self.raw_decode(s, idx=_w(s, 0).end())#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             raise JSONDecodeError("Expecting value", s, err.value) from None#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                         json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[94mRedQueen#033[0;39m - Version 1.0.40 in master - Locked for local changes!#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mSpeller#033[0;39m - Version 1.1.13 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mTelemetry#033[0;39m - Version 1.3.5 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mUnitConverter#033[0;39m - Version 1.0.5 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      #033[32mWikipedia#033[0;39m - Version 2.0.3 in master#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillManager]                      Found 0 skill update#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[ConfigManager]                     Checking configuration for skill #033[1mAliceCore#033[0;39m#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[ConfigManager]                     Checking configuration for skill #033[1mCalculator#033[0;39m#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[ConfigManager]                     Checking configuration for skill #033[1mContextSensitive#033[0;39m#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: Traceback (most recent call last):
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 138, in onStart
Jan 15 17:09:56 ProjectAlice python[2495]:     skillManager.onStart()
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 180, in onStart
Jan 15 17:09:56 ProjectAlice python[2495]:     self.initSkills()
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 552, in initSkills
Jan 15 17:09:56 ProjectAlice python[2495]:     installFile = json.loads(installFilePath.read_text())
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Jan 15 17:09:56 ProjectAlice python[2495]:     return _default_decoder.decode(s)
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Jan 15 17:09:56 ProjectAlice python[2495]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 15 17:09:56 ProjectAlice python[2495]:   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
Jan 15 17:09:56 ProjectAlice python[2495]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Jan 15 17:09:56 ProjectAlice python[2495]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Project Alice Logger]              Error while starting managers: Expecting value: line 1 column 1 (char 0)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                         Traceback (most recent call last):#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 138, in onStart#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             skillManager.onStart()#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 180, in onStart#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             self.initSkills()#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/home/pi/ProjectAlice/core/base/SkillManager.py", line 552, in initSkills#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             installFile = json.loads(installFilePath.read_text())#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/#033[4minit#033[0;31m.py", line 348, in loads#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             return _default_decoder.decode(s)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/decoder.py", line 337, in decode#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             obj, end = self.raw_decode(s, idx=_w(s, 0).end())#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                           File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                             raise JSONDecodeError("Expecting value", s, err.value) from None#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[31m[Traceback]                         json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[Project Alice]                     Shutting down#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[AliceWatchManager]                 Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[ApiManager]                        Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SnipsAsr]                          Stopping Snips Asr#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[DialogManager]                     Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[MultiIntentManager]                Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[SkillStoreManager]                 Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[TelemetryManager]                  Stopping#033[0m
Jan 15 17:09:56 ProjectAlice python[2495]: #033[39m[ThreadManager]                     Stopping#033[0m
Jan 15 17:09:57 ProjectAlice python[2495]: #033[39m[TimeManager]                       Stopping#033[0m
Jan 15 17:09:57 ProjectAlice python[2495]: #033[39m[TTSManager]                        Stopping#033[0m
Jan 15 17:09:57 ProjectAlice python[2495]: #033[39m[WakewordManager]                   Stopping#033[0m
Jan 15 17:09:57 ProjectAlice python[2495]: #033[39m[SnipsWakeword]                     Stopping #033[1mSnips hotword#033[0;39m#033[0m
Jan 15 17:09:57 ProjectAlice python[2495]: #033[39m[WebUIManager]                      Stopping#033[0m
Jan 15 17:09:58 ProjectAlice systemd[1]: Stopping A high performance web server and a reverse proxy server...
Jan 15 17:09:58 ProjectAlice systemd[1]: nginx.service: Succeeded.
Jan 15 17:09:58 ProjectAlice systemd[1]: Stopped A high performance web server and a reverse proxy server.
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[WebUIManager]                      Stopped nginx server#033[0m
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[BugReportManager]                  Stopping#033[0m
Jan 15 17:09:58 ProjectAlice systemd[1]: /etc/systemd/system/hermesledcontrol.service:5: Neither a valid executable name nor an absolute path: WorkingDirectory=/home/pi/HermesLedControl/venv/bin/python
Jan 15 17:09:58 ProjectAlice systemd[1]: /etc/systemd/system/hermesledcontrol.service:5: Neither a valid executable name nor an absolute path: WorkingDirectory=/home/pi/HermesLedControl/venv/bin/python
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[Project Alice]                     Started in 15.16 seconds#033[0m
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[Project Alice]                     Shutting down#033[0m
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[SnipsAsr]                          Stopping Snips Asr#033[0m
Jan 15 17:09:58 ProjectAlice python[2495]: #033[33m[SubprocessManager]                 Tried terminating the subprocess SnipsASR, but it was not found#033[0m
Jan 15 17:09:58 ProjectAlice systemd[1]: /etc/systemd/system/hermesledcontrol.service:5: Neither a valid executable name nor an absolute path: WorkingDirectory=/home/pi/HermesLedControl/venv/bin/python
Jan 15 17:09:58 ProjectAlice python[2495]: #033[39m[Project Alice]                     Shutdown completed, see you soon!#033[0m
Jan 15 17:09:59 ProjectAlice systemd[1]: ProjectAlice.service: Succeeded.
Jan 15 17:10:04 ProjectAlice systemd[1]: ProjectAlice.service: Service RestartSec=5s expired, scheduling restart.
```
During this time it is almost impossible to log in via the WebUI, and when that is successful it is extremely buggy.

**Comment by Psychokiller1888** [comment]
Should be mitigated by a fix yesterday
