### ISSUE TITLE
[AUTO BUG REPORT] requests.exceptions.SSLError: HTTPSConnectionPool(host='skills.projectalice.io', port=443): Max retries exceeded with url: /assets/store/skills.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)')))

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#660]
```
[CommonsManager]                    --Initializing--
[StateManager]                      --Initializing--
[SubprocessManager]                 --Initializing--
[ConfigManager]                     --Initializing--
[ConfigManager]                     Checking Alice configuration file
[DatabaseManager]                   --Initializing--
[SkillManager]                      --Initializing--
[WidgetManager]                     --Initializing--
[DeviceManager]                     --Initializing--
[AudioManager]                      --Initializing--
[LanguageManager]                   --Initializing--
[LanguageManager]                   Active language set to **en-US**
[LanguageManager]                   Default language set to **en-US**
[ASRManager]                        --Initializing--
[TTSManager]                        --Initializing--
[ThreadManager]                     --Initializing--
[MqttManager]                       --Initializing--
[TimeManager]                       --Initializing--
[UserManager]                       --Initializing--
[MultiIntentManager]                --Initializing--
[TelemetryManager]                  --Initializing--
[LocationManager]                   --Initializing--
[InternetManager]                   --Initializing--
[WakewordRecorder]                  --Initializing--
[TalkManager]                       --Initializing--
[WebUIManager]                      --Initializing--
[ApiManager]                        --Initializing--
[NodeRedManager]                    --Initializing--
[SkillStoreManager]                 --Initializing--
[DialogTemplateManager]             --Initializing--
[AssistantManager]                  --Initializing--
[NluManager]                        --Initializing--
[AliceWatchManager]                 --Initializing--
[DialogManager]                     --Initializing--
[WakewordManager]                   --Initializing--
[WebUINotificationManager]          --Initializing--
[BugReportManager]                  Starting
[CommonsManager]                    Starting
[StateManager]                      Starting
[ThreadManager]                     Started new thread **subprocessManager**, thread count: 1
[ConfigManager]                     Starting
[LanguageManager]                   Starting
[WebUINotificationManager]          Starting
[LocationManager]                   Starting
[LocationManager]                   Loaded location **Home**
[LocationManager]                   Loaded location **Outside**
[LocationManager]                   Loaded location **Bedroom**
[LocationManager]                   Loaded location **Bathroom**
[LocationManager]                   Loaded location **Inside**
[LocationManager]                   Loaded location **Entrance**
[LocationManager]                   Loaded location **Lounge**
[LocationManager]                   Loaded location **Kitchen**
[LocationManager]                   Loaded location **StoreRoom**
[LocationManager]                   Loaded location **Ute**
[LocationManager]                   Loaded **10** locations
[AudioManager]                      Starting
[AudioManager]                      Using **seeed-4mic-voicecard: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 (hw:1,0)** for audio input
[AudioManager]                      Using **bcm2835 Headphones: - (hw:0,0)** for audio output
[InternetManager]                   Starting
[ThreadManager]                     Started new thread **internetCheckThread**, thread count: 3
[DatabaseManager]                   Starting
[UserManager]                       Starting
[UserManager]                       Loaded **2** users
[MqttManager]                       Starting
[AliceWatchManager]                 Starting
[ApiManager]                        Starting
[ThreadManager]                     Started new thread **API**, thread count: 5
[ASRManager]                        Starting
[GoogleAsr]                         Checking dependencies
[GoogleAsr]                         Starting Google Asr
[DialogManager]                     Starting
[MultiIntentManager]                Starting
[SkillStoreManager]                 Starting
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
[Traceback]                             chunked=chunked,
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 382, in _make_request
[Traceback]                             self._validate_conn(conn)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
[Traceback]                             conn.connect()
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connection.py", line 421, in connect
[Traceback]                             tls_in_tls=tls_in_tls,
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
[Traceback]                             sock, context, tls_in_tls, server_hostname=server_hostname
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
[Traceback]                             return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
[Traceback]                           File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
[Traceback]                             session=session
[Traceback]                           File "/usr/lib/python3.7/ssl.py", line 853, in _create
[Traceback]                             self.do_handshake()
[Traceback]                           File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
[Traceback]                             self._sslobj.do_handshake()
[Traceback]                         ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
[Traceback]                             timeout=timeout
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
[Traceback]                             method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 574, in increment
[Traceback]                             raise MaxRetryError(_pool, url, error or ResponseError(cause))
[Traceback]                         urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='skills.projectalice.io', port=443): Max retries exceeded with url: /assets/store/skills.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)')))
[Traceback]                         During handling of the above exception, another exception occurred:
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/core/base/SuperManager.py", line 134, in onStart
[Traceback]                             manager.onStart()
[Traceback]                           File "/home/pi/ProjectAlice/core/base/SkillStoreManager.py", line 50, in onStart
[Traceback]                             self.refreshStoreData()
[Traceback]                           File "/home/pi/ProjectAlice/core/util/Decorators.py", line 158, in offlineDecorator
[Traceback]                             return func(*args, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/core/base/SkillStoreManager.py", line 64, in refreshStoreData
[Traceback]                             req = requests.get(url=constants.SKILLS_STORE_ASSETS)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 75, in get
[Traceback]                             return request('get', url, params=params, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/api.py", line 61, in request
[Traceback]                             return session.request(method=method, url=url, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
[Traceback]                             resp = self.send(prep, **send_kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
[Traceback]                             r = adapter.send(request, **kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/requests/adapters.py", line 517, in send
[Traceback]                             raise SSLError(e, request=request)
[Traceback]                         requests.exceptions.SSLError: HTTPSConnectionPool(host='skills.projectalice.io', port=443): Max retries exceeded with url: /assets/store/skills.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)')))
[Project Alice Logger]              Error while starting managers: HTTPSConnectionPool(host='skills.projectalice.io', port=443): Max retries exceeded with url: /assets/store/skills.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: EE certificate key too weak (_ssl.c:1056)')))
[Project Alice]                     Shutting down
[AliceWatchManager]                 Stopping
[ApiManager]                        Stopping
[GoogleAsr]                         Stopping Google Asr
[DialogManager]                     Stopping
[MultiIntentManager]                Stopping
[SkillStoreManager]                 Stopping
[TelemetryManager]                  Stopping
[ThreadManager]                     Stopping
[TimeManager]                       Stopping
[TTSManager]                        Stopping
[WakewordManager]                   Stopping
[WebUIManager]                      Stopping
[WebUIManager]                      Stopped nginx server
[BugReportManager]                  Stopping
```

**Comment by Psychokiller1888** [comment]
Hmmm, this I don't get....
When browsing to https://skills.projectalice.io/assets/store/skills.json, the url that fails, the SSL certificate is valid

**Comment by LazzaAU** [comment]
im back in a bad internet zone so maybe poor internet is a related factor ? as it only seemed to happen around the time my internet dropped out for a decent period of time.
