### ISSUE TITLE
[AUTO BUG REPORT] AttributeError: 'NoneType' object has no attribute 'lastWasSoundPlayOnly'

### ISSUE THREAD

**Issue by LazzaAU** [project-alice-assistant/ProjectAlice#662]
```
[CommonsManager]                    --Initializing--
[StateManager]                      --Initializing--
[SubprocessManager]                 --Initializing--
[ConfigManager]                     --Initializing--
[ConfigManager]                     Checking Alice configuration file
[ConfigManager]                     Deprecated configuration: **aliceIp**
[ConfigManager]                     Deprecated configuration: **aliceVersion**
[DatabaseManager]                   --Initializing--
[SkillManager]                      --Initializing--
[WidgetManager]                     --Initializing--
[DeviceManager]                     --Initializing--
[AudioManager]                      --Initializing--
[LanguageManager]                   --Initializing--
[LanguageManager]                   Active language set to **en-US**
[LanguageManager]                   Default language set to **en-US**
[ASRManager]                        --Initializing--
[TTSManager]                        --Initializing--
[ThreadManager]                     --Initializing--
[MqttManager]                       --Initializing--
[TimeManager]                       --Initializing--
[UserManager]                       --Initializing--
[MultiIntentManager]                --Initializing--
[TelemetryManager]                  --Initializing--
[LocationManager]                   --Initializing--
[InternetManager]                   --Initializing--
[WakewordRecorder]                  --Initializing--
[TalkManager]                       --Initializing--
[WebUIManager]                      --Initializing--
[ApiManager]                        --Initializing--
[NodeRedManager]                    --Initializing--
[SkillStoreManager]                 --Initializing--
[DialogTemplateManager]             --Initializing--
[AssistantManager]                  --Initializing--
[NluManager]                        --Initializing--
[AliceWatchManager]                 --Initializing--
[DialogManager]                     --Initializing--
[WakewordManager]                   --Initializing--
[WebUINotificationManager]          --Initializing--
[BugReportManager]                  Starting
[CommonsManager]                    Starting
[StateManager]                      Starting
[ThreadManager]                     Started new thread **subprocessManager**, thread count: 1
[ConfigManager]                     Starting
[LanguageManager]                   Starting
[WebUINotificationManager]          Starting
[LocationManager]                   Starting
[LocationManager]                   Loaded location **Home**
[LocationManager]                   Loaded location **Outside**
[LocationManager]                   Loaded location **Bedroom**
[LocationManager]                   Loaded location **Bathroom**
[LocationManager]                   Loaded location **Inside**
[LocationManager]                   Loaded location **Entrance**
[LocationManager]                   Loaded location **Lounge**
[LocationManager]                   Loaded location **Kitchen**
[LocationManager]                   Loaded location **StoreRoom**
[LocationManager]                   Loaded location **Ute**
[LocationManager]                   Loaded **10** locations
[AudioManager]                      Starting
[AudioManager]                      Using **seeed-4mic-voicecard: bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0 (hw:1,0)** for audio input
[AudioManager]                      Using **bcm2835 Headphones: - (hw:0,0)** for audio output
[InternetManager]                   Starting
[ThreadManager]                     Started new thread **internetCheckThread**, thread count: 3
[DatabaseManager]                   Starting
[UserManager]                       Starting
[UserManager]                       Loaded **2** users
[MqttManager]                       Starting
[AliceWatchManager]                 Starting
[ApiManager]                        Starting
[ThreadManager]                     Started new thread **API**, thread count: 5
[ASRManager]                        Starting
[CoquiAsr]                          Checking dependencies
[CoquiAsr]                          Starting Coqui Asr
[CoquiAsr]                          Loading Model
[CoquiAsr]                          Model Loaded
[CoquiAsr]                          Scorer Loaded
[CoquiAsr]                          Checking dependencies
[DialogManager]                     Starting
[MultiIntentManager]                Starting
[SkillStoreManager]                 Starting
[TelemetryManager]                  Starting
[ThreadManager]                     Starting
[TimeManager]                       Starting
[TTSManager]                        Starting
[AmazonTts]                         Checking dependencies
[AmazonTts]                         Language from config: **en-GB**
[AmazonTts]                         Type from config: **female**
[AmazonTts]                         Voice from config: **Amy**
[PicoTts]                           Checking dependencies
[WakewordManager]                   Starting
[SnipsWakeword]                     Checking dependencies
[SnipsWakeword]                     Starting **Snips hotword**
[SubprocessManager]                 Starting the subprocess SnipsHotword
[WebUIManager]                      Starting
[WebUIManager]                      Started nginx server
[ThreadManager]                     Started new thread **DisplayResourceUsage**, thread count: 6
[TalkManager]                       Starting
[NluManager]                        Starting
[SkillManager]                      Starting
[SkillManager]                      Checking for skill updates
[SkillManager]                      ![green](AliceCore) - Version 1.7.0 in master
[SkillManager]                      ![red](Skill **AliceDevTools**) is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      ![green](AliceVolume) - Version 1.0.17 in master
[SkillManager]                      ![green](BackUpAlice) - Version 1.1.12 in master
[WebUINotificationManager]          Adding notification[586]: Skill update available
[SkillManager]                      ![blue](ContextSensitive) - Version 1.0.33 < 1.0.35 in master - Locked for local changes!
[SkillManager]                      ![green](DateDayTimeYear) - Version 1.1.5 in master
[SkillManager]                      ![red](Skill **GPSDtoMQTT**) is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      ![green](HLCpattern) - Version 1.1.5 in master
[WebUINotificationManager]          Adding notification[587]: Skill update available
[SkillManager]                      ![blue](HomeAssistant) - Version 3.1.9 < 3.2.1 in master - Locked for local changes!
[SkillManager]                      ![green](OvenTemperatureConversion) - Version 1.0.14 in master
[WebUINotificationManager]          Adding notification[588]: Skill update available
[SkillManager]                      ![blue](RedQueen) - Version 1.0.40 < 1.0.41 in master - Locked for local changes!
[SkillManager]                      ![green](Reminder) - Version 1.2.6 in master
[SkillManager]                      ![green](Telegram) - Version 1.5.5 in master
[SkillManager]                      ![green](Telemetry) - Version 1.3.7 in master
[SkillManager]                      ![red](Skill **WaterTankLevel**) is not available on Github. Deprecated or is it a dev skill?
[SkillManager]                      Found 0 skill update
[ConfigManager]                     Checking configuration for skill **AliceCore**
[ConfigManager]                     Checking configuration for skill **AliceDevTools**
[ConfigManager]                     Checking configuration for skill **AliceVolume**
[ConfigManager]                     Checking configuration for skill **BackUpAlice**
[ConfigManager]                     Checking configuration for skill **ContextSensitive**
[ConfigManager]                     Checking configuration for skill **DateDayTimeYear**
[ConfigManager]                     Checking configuration for skill **GPSDtoMQTT**
[ConfigManager]                     Checking configuration for skill **HLCpattern**
[ConfigManager]                     Checking configuration for skill **HomeAssistant**
[ConfigManager]                     Checking configuration for skill **OvenTemperatureConversion**
[ConfigManager]                     Checking configuration for skill **RedQueen**
[ConfigManager]                     Checking configuration for skill **Reminder**
[ConfigManager]                     Checking configuration for skill **Telegram**
[ConfigManager]                     Checking configuration for skill **Telemetry**
[ConfigManager]                     Checking configuration for skill **WaterTankLevel**
[AliceCore]                         Starting
[AliceCore]                         Found **2** device type
[AliceCore]                         ![green](Started!)
[AliceDevTools]                     Starting
[AliceDevTools]                     ![green](Started!)
[AliceVolume]                       Starting
[AliceVolume]                       ![green](Started!)
[BackUpAlice]                       Starting
[BackUpAlice]                       ![green](Started!)
[ContextSensitive]                  Starting
[ContextSensitive]                  ![green](Started!)
[DateDayTimeYear]                   Starting
[DateDayTimeYear]                   Found **2** widgets
[DateDayTimeYear]                   ![green](No widget config template for widget type Clock found)
[DateDayTimeYear]                   ![green](No widget config template for widget type Date found)
[DateDayTimeYear]                   ![green](Started!)
[GPSDtoMQTT]                        Starting
[GPSDtoMQTT]                        ![green](Started!)
[HLCpattern]                        Starting
[HLCpattern]                        ![green](Started!)
[HomeAssistant]                     Starting
[HomeAssistant]                     Found **10** device type
[HomeAssistant]                     ![green](Started!)
[OvenTemperatureConversion]         Starting
[OvenTemperatureConversion]         ![green](Started!)
[RedQueen]                          Starting
[RedQueen]                          ![green](Started!)
[RedQueen]                          Found existing Red Queen identity
[Reminder]                          Starting
[Reminder]                          ![green](Started!)
[Reminder]                          Doing database maintenance
[Reminder]                          Checking for active timers in MyReminders database
[Reminder]                          Checking for active timers in MyTimer database
[Reminder]                          Checking for active timers in MyAlarm database
[Telegram]                          Starting
[Telegram]                          ![green](Started!)
[Telegram]                          Loaded 1 user
[Telemetry]                         Starting
[Telemetry]                         ![green](Started!)
[WaterTankLevel]                    Starting
[WaterTankLevel]                    ![green](Started!)
[SkillManager]                      Skills started. 65 intents supported
[DeviceManager]                     Starting
[DeviceManager]                     Loaded **63** device instance
[WidgetManager]                     Starting
[WidgetManager]                     Loaded **2** pages
[WidgetManager]                     Loaded **2** templates from 1 skill
[WidgetManager]                     Loaded 1 active widget
[DialogTemplateManager]             Starting
[AssistantManager]                  Starting
[AssistantManager]                  Checking assistant
[AssistantManager]                  Assistant seems consistent
[DialogTemplateManager]             Checking data for skill **AliceCore**
[DialogTemplateManager]             Checking data for skill **AliceDevTools**
[DialogTemplateManager]             Checking data for skill **AliceVolume**
[DialogTemplateManager]             Checking data for skill **BackUpAlice**
[DialogTemplateManager]             Checking data for skill **ContextSensitive**
[DialogTemplateManager]             Checking data for skill **DateDayTimeYear**
[DialogTemplateManager]             Checking data for skill **GPSDtoMQTT**
[DialogTemplateManager]             Checking data for skill **HLCpattern**
[DialogTemplateManager]             Checking data for skill **HomeAssistant**
[DialogTemplateManager]             Checking data for skill **OvenTemperatureConversion**
[DialogTemplateManager]             Checking data for skill **RedQueen**
[DialogTemplateManager]             Checking data for skill **Reminder**
[DialogTemplateManager]             Checking data for skill **Telegram**
[DialogTemplateManager]             Checking data for skill **Telemetry**
[DialogTemplateManager]             Checking data for skill **WaterTankLevel**
[DialogTemplateManager]             Cache uptodate
[NodeRedManager]                    Starting
[AudioManager]                      Starting audio publisher
[ThreadManager]                     Started new thread **audioPublisher**, thread count: 11
[ThreadManager]                     Started new thread **checkHeartbeats**, thread count: 13
[ThreadManager]                     Started new thread **heartBeatThread-1661083818**, thread count: 13
[GPSDtoMQTT]                        Connected to GPS MQTT Broker!........
[HomeAssistant]                     HomeAssistant Connected
[HomeAssistant]                     Sending Heartbeat connection requests
[DeviceManager]                     Device named **heater state** (c5184bcf-65c2-4390-902b-5bb525ebe2b4) in Bedroom connected
[DeviceManager]                     Device named **alarm** (0ee62473-660d-49c4-ba73-5d5f8e591fce) in Lounge connected
[DeviceManager]                     Device named **people home** (7bd42d49-ec11-4735-aa56-ff0030712715) in Lounge connected
[DeviceManager]                     Device named **awning switch - on is open** (0655f95e-f775-48c8-a176-35fe56d99b83) in Outside connected
[DeviceManager]                     Device named **rain water hose connected** (87af7090-1885-4107-99bb-3699aa7f5ea5) in Kitchen connected
[DeviceManager]                     Device named **rain water low level** (108bd0cb-b45a-4731-a9eb-2baf845463bf) in Outside connected
[DeviceManager]                     Device named **rain water mid level** (cf91f500-9a4b-45a5-98e7-276ddb57e760) in Outside connected
[DeviceManager]                     Device named **rain water high level** (3f59590a-cb93-4104-a4d0-94d7aaf77efb) in Outside connected
[DeviceManager]                     Device named **rain water pump running** (326a3433-8ab4-4a03-b55f-161118231964) in Kitchen connected
[DeviceManager]                     Device named **kitchen lights** (2d65223c-79eb-48a9-910b-d5dd89e25adb) in Inside connected
[DeviceManager]                     Device named **bedroom lights** (8f6bff74-3db1-4638-8cda-74f039ed27d7) in Bedroom connected
[DeviceManager]                     Device named **bathroom lights** (bb7a59cc-f9fb-4ee3-888d-168936908657) in Bathroom connected
[DeviceManager]                     Device named **lounge lights** (b89b2e4a-d397-4eaa-865e-1006218967ac) in Lounge connected
[DeviceManager]                     Device named **outside lights** (848a1211-9e0a-453f-bbaf-0264f19149d5) in Outside connected
[DeviceManager]                     Device named **all main lights** (70fc6fe5-98c3-4dae-8a74-93f189f41f34) in Home connected
[DeviceManager]                     Device named **laptop charger** (ae8e6f5a-68ef-4bc6-ad44-1def58a2a9aa) in Lounge connected
[DeviceManager]                     Device named **pillow light** (950190b5-a8f8-488b-be85-7e26e44d6cbd) in Bedroom connected
[DeviceManager]                     Device named **external light** (d9622b15-a1c4-41c8-93b5-28abab151b85) in Outside connected
[DeviceManager]                     Device named **pillow light** (0ef4ff43-fb07-4982-9d73-a77cb97996a8) in Bedroom connected
[DeviceManager]                     Device named **awning light** (34709c08-4239-47eb-85d7-4780bc7ec3b1) in Outside connected
[DeviceManager]                     Device named **couch light** (f62983f5-e18d-4e65-a29e-1a766a658b89) in Lounge connected
[DeviceManager]                     Device named **window light** (9ed3c3b2-2647-4c1b-a25a-ca8dcf3dd090) in Bedroom connected
[DeviceManager]                     Device named **witi** (47afe2b6-97a4-4586-86a8-8c281e8cb0a7) in Lounge connected
[DeviceManager]                     Device named **sink light** (42141829-be1f-4f67-8a58-d005f5c66a4e) in Kitchen connected
[DeviceManager]                     Device named **awning light** (005284fd-1834-4f0b-8dd0-99698b06fa27) in Outside connected
[DeviceManager]                     Device named **window light** (c92f4189-376a-4172-9f3c-ba8a6fa5921b) in Bedroom connected
[DeviceManager]                     Device named **couch light** (d05fa1dd-3a1e-4641-8ceb-b306f1f7d6f7) in Lounge connected
[DeviceManager]                     Device named **round lights** (6b58eb1c-8100-4a4d-a948-ba9b462cf4c3) in Kitchen connected
[DeviceManager]                     Device named **toilet light** (03370462-de54-4327-96d9-9662e1eb8372) in Bathroom connected
[DeviceManager]                     Device named **mirror light** (4a419d94-b223-4ca9-8421-afc60284af69) in Bathroom connected
[DeviceManager]                     Device named **external light** (5c9f7cc0-c07d-4f3b-b811-bb1ae10d6180) in Outside connected
[DeviceManager]                     Device named **fridge fan** (9bc27783-75fa-4590-8b70-65f9eba9f459) in Kitchen connected
[DeviceManager]                     Device named **240 power** (3e8ddadd-df80-4036-a9d8-9085016c78a7) in Entrance connected
[DeviceManager]                     Device named **diesel heater on** (ecb257c6-79e0-47f0-884f-707c5c9b101d) in Bedroom connected
[DeviceManager]                     Device named **diesel heater off** (24199336-122f-4243-a101-8503eae2e9de) in Bedroom connected
[DeviceManager]                     Device named **main light** (de3eea51-d152-4a17-8bfc-b27f9b192172) in Bedroom connected
[DeviceManager]                     Device named **entrance light** (7a373414-542a-4d54-b186-0de397055b63) in Entrance connected
[DeviceManager]                     Device named **rain water pump** (9f26279c-e49e-4b76-9977-5af2c568d427) in Kitchen connected
[DeviceManager]                     Device named **toilet motion** (423aa33e-e58e-49ae-ab64-aad3d50e57ca) in Bathroom connected
[DeviceManager]                     Device named **outside temperature** (afbcbe80-f42c-47f1-85e1-bc96e4b6d924) in Outside connected
[DeviceManager]                     Device named **outside humidity** (1b9f2cb9-49ef-4274-8b53-26ce391d0f0f) in Outside connected
[DeviceManager]                     Device named **outside pressure** (9a6936fe-7843-40ba-b651-a71767fcb069) in Outside connected
[DeviceManager]                     Device named **inside temperature** (879104e0-aabb-4d78-b0ef-2b97654fc44f) in Inside connected
[DeviceManager]                     Device named **inside humidity** (bdd4e9a3-01f6-4f6d-bfae-24eeaea73261) in Inside connected
[DeviceManager]                     Device named **inside dewpoint** (3509172c-e560-4cbe-8984-622a1b8ef1b9) in Inside connected
[DeviceManager]                     Device named **inside pressure** (813f3961-e167-4ad9-a57a-992b4895cc51) in Inside connected
[DeviceManager]                     Device named **inside gas** (8553c120-4dd0-41eb-b84a-588f64bdb3a7) in Inside connected
[DeviceManager]                     Device named **rain water tank** (f6e97126-cb36-4ec7-94f6-64a583216ef6) in StoreRoom connected
[DeviceManager]                     Device named **fresh water tank 1** (110229ea-835f-4fef-a580-4b4bdde18b23) in StoreRoom connected
[DeviceManager]                     Device named **fresh water tank 2** (0d30b82d-2bba-4add-bb2e-b66704f95113) in StoreRoom connected
[DeviceManager]                     Device named **larrys presence home** (a8cc002f-8d9d-4d08-a176-7b560e42eee1) in Outside connected
[DeviceManager]                     Device named **everyone home** (f73238b6-c2ad-4e7a-82bb-4b07ec40f1db) in Outside connected
[DeviceManager]                     Device named **rainwater valve** (99ba1740-7565-40ca-b04a-229021448d57) in Outside connected
[DeviceManager]                     Device named **240 power** (22f875fc-cd20-4579-9a38-da3b15fe988a) in Entrance connected
[DeviceManager]                     Device named **rmpro temperature** (8c5858fa-2605-4d3b-a1d4-cf0be873def9) in Entrance connected
[DeviceManager]                     Device named **larry's s20fe battery level** (57fdebcd-bccd-4812-925d-0c83a45e5a28) in Lounge connected
[DeviceManager]                     Device named **larry's s20fe battery temperature** (87a7ec28-89a9-4ccc-b6e6-c5bfe6fb4f8f) in Lounge connected
[DeviceManager]                     Device named **grey water tank 1** (f2a7ede0-9469-4618-8e7b-f545c7d28103) in StoreRoom connected
[DeviceManager]                     Device named **sues phone battery level** (5ddd5b4e-c461-47b3-a6da-08160b298394) in Lounge connected
[DeviceManager]                     Device named **sues phone battery temperature** (2034be4b-69a3-4057-8a66-fe52ae5c90c2) in Lounge connected
[DeviceManager]                     Device named **ute battery voltage adc** (7fb7bd9b-d193-4b08-a6d4-8d1094b304cb) in StoreRoom connected
[SnipsNlu]                          Starting Snips NLU
[SubprocessManager]                 Starting the subprocess SnipsNLU
[Project Alice]                     Started in 44.77 seconds
[AudioManager]                      Playing wav stream using **bcm2835 Headphones: - (hw:0,0)** audio output from device **Alice** (channels: 1, rate: 16000)
[AudioManager]                      Playing bytes finished
[Traceback]                         Traceback (most recent call last):
[Traceback]                           File "/home/pi/ProjectAlice/venv/lib/python3.7/site-packages/paho/mqtt/client.py", line 3556, in _handle_on_message
[Traceback]                             callback(self, self._userdata, message)
[Traceback]                           File "/home/pi/ProjectAlice/core/server/MqttManager.py", line 667, in topicPlayBytes
[Traceback]                             self.broadcast(method=constants.EVENT_PLAY_BYTES, exceptions=self.name, propagateToSkills=True, payload=msg.payload, deviceUid=deviceUid, sessionId=sessionId)
[Traceback]                           File "/home/pi/ProjectAlice/core/base/model/ProjectAliceObject.py", line 136, in broadcast
[Traceback]                             func(**kwargs)
[Traceback]                           File "/home/pi/ProjectAlice/core/server/AudioServer.py", line 302, in onPlayBytes
[Traceback]                             if not session.lastWasSoundPlayOnly:
[Traceback]                         AttributeError: 'NoneType' object has no attribute 'lastWasSoundPlayOnly'
[MqttManager]                       Caught exception in user defined callback function topicPlayBytes: 'NoneType' object has no attribute 'lastWasSoundPlayOnly'
[DeviceManager]                     Device **WebInterface** has not given a signal since 5 seconds or more
[DeviceManager]                     Device named **WebInterface** (b8e753ab-3324-49db-a5e3-9722ea9d6644) in Home disconnected
[Project Alice]                     Shutting down
[SkillManager]                      Stopping
[AliceCore]                         ![green](Stopped)
[AliceDevTools]                     ![green](Stopped)
[AliceVolume]                       ![green](Stopped)
[BackUpAlice]                       ![green](Stopped)
[ContextSensitive]                  ![green](Stopped)
[DateDayTimeYear]                   ![green](Stopped)
[GPSDtoMQTT]                        ![green](Stopping GPSD MQTT connection)
[GPSDtoMQTT]                        ![green](Stopped)
[HLCpattern]                        ![green](Stopped)
[HomeAssistant]                     ![green](Backing up dialog file)
[HomeAssistant]                     ![green](Stopped)
[OvenTemperatureConversion]         ![green](Stopped)
[RedQueen]                          ![green](Stopped)
[Reminder]                          ![green](Stopped)
[Telegram]                          ![green](Stopped)
[Telemetry]                         ![green](Stopped)
[WaterTankLevel]                    ![green](Stopped)
[AliceWatchManager]                 Stopping
[ApiManager]                        Stopping
[CoquiAsr]                          Stopping Coqui Asr
[DialogManager]                     Stopping
[MultiIntentManager]                Stopping
[SkillStoreManager]                 Stopping
[TelemetryManager]                  Stopping
[ThreadManager]                     Stopping
[TimeManager]                       Stopping
[TTSManager]                        Stopping
[WakewordManager]                   Stopping
[SnipsWakeword]                     Stopping **Snips hotword**
[WebUIManager]                      Stopping
[WebUIManager]                      Stopped nginx server
[ConfigManager]                     Stopping
[AudioManager]                      Stopping
[LanguageManager]                   Stopping
[LocationManager]                   Stopping
[DeviceManager]                     Stopping
[ThreadManager]                     Terminated thread **heartBeatThread-1661083818**, thread count: 7
[TalkManager]                       Stopping
[DatabaseManager]                   Stopping
[UserManager]                       Stopping
[WebUINotificationManager]          Stopping
[WidgetManager]                     Stopping
[DialogTemplateManager]             Stopping
[AssistantManager]                  Stopping
[NluManager]                        Stopping
[SnipsNlu]                          Stopping Snips NLU
[InternetManager]                   Stopping
[NodeRedManager]                    Stopping
[StateManager]                      Stopping
[SubprocessManager]                 Stopping
[MqttManager]                       Stopping
[BugReportManager]                  Stopping
```

**Comment by LazzaAU** [comment]
Been getting this alot recently but i think i had my recurse gitpull of submodules a little F'd up. Have just fixed up my bash script and seems ok ... for now :)
i'll close this tomorrow if it remains good

**Comment by LazzaAU** [comment]
Hasn't been a issue in the last 20 odd starts since fixing my script for git pulling. Think it was not doing the recurse of the modules properly and therefore missing a update. Once i fixed that it updated to the latest audioserver file and seems fine now

closing
